# coding: utf-8

"""
    BambooHR API

    BambooHR API documentation. https://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bamboohr_sdk.api.total_rewards_api import TotalRewardsApi


# WARNING: This file is auto-generated by openapi-generator during `make generate`.
# Once you add real test implementations, protect this file from being overwritten
# by adding it to .openapi-generator-ignore:
#
#     test/test_total_rewards_api.py
#
# See README.md for details on protecting implemented tests.


class TestTotalRewardsApi(unittest.TestCase):
    """TotalRewardsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TotalRewardsApi()

    def tearDown(self) -> None:
        pass

    def test_add_total_rewards_employees(self) -> None:
        """Test case for add_total_rewards_employees

        Add Employees to Total Rewards
        """
        pass

    def test_check_total_rewards_profile(self) -> None:
        """Test case for check_total_rewards_profile

        Check Total Rewards Profile Availability
        """
        pass

    def test_get_total_rewards_printable_statement(self) -> None:
        """Test case for get_total_rewards_printable_statement

        Get Printable Total Rewards Statement
        """
        pass

    def test_get_total_rewards_statement(self) -> None:
        """Test case for get_total_rewards_statement

        Get Total Rewards Statement
        """
        pass

    def test_remove_total_rewards_custom_disclaimer(self) -> None:
        """Test case for remove_total_rewards_custom_disclaimer

        Remove Total Rewards Custom Disclaimer
        """
        pass

    def test_remove_total_rewards_employees(self) -> None:
        """Test case for remove_total_rewards_employees

        Remove Employees from Total Rewards
        """
        pass

    def test_set_total_rewards_custom_disclaimer(self) -> None:
        """Test case for set_total_rewards_custom_disclaimer

        Set Total Rewards Custom Disclaimer
        """
        pass

    def test_set_total_rewards_onboarding_step(self) -> None:
        """Test case for set_total_rewards_onboarding_step

        Set Total Rewards Onboarding Step Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
