# coding: utf-8

"""
    BambooHR API

    BambooHR API documentation. https://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bamboohr_sdk.api.tabular_data_api import TabularDataApi


# WARNING: This file is auto-generated by openapi-generator during `make generate`.
# Once you add real test implementations, protect this file from being overwritten
# by adding it to .openapi-generator-ignore:
#
#     test/test_tabular_data_api.py
#
# See README.md for details on protecting implemented tests.


class TestTabularDataApi(unittest.TestCase):
    """TabularDataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TabularDataApi()

    def tearDown(self) -> None:
        pass

    def test_add_employee_table_row(self) -> None:
        """Test case for add_employee_table_row

        Create Table Row
        """
        pass

    def test_add_employee_table_row_v1(self) -> None:
        """Test case for add_employee_table_row_v1

        Create Table Row v1.1
        """
        pass

    def test_delete_employee_table_row_v1(self) -> None:
        """Test case for delete_employee_table_row_v1

        Delete Table Row
        """
        pass

    def test_get_changed_employee_table_data(self) -> None:
        """Test case for get_changed_employee_table_data

        Get Changed Employee Table Data
        """
        pass

    def test_get_employee_table_row(self) -> None:
        """Test case for get_employee_table_row

        Get Employee Table Rows
        """
        pass

    def test_update_employee_table_row(self) -> None:
        """Test case for update_employee_table_row

        Update Table Row
        """
        pass

    def test_update_employee_table_row_v(self) -> None:
        """Test case for update_employee_table_row_v

        Update Table Row v1.1
        """
        pass


if __name__ == '__main__':
    unittest.main()
