# coding: utf-8

"""
    BambooHR API

    BambooHR API documentation. https://documentation.bamboohr.com/

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bamboohr_sdk.api.pay_grades_bands_api import PayGradesBandsApi


# WARNING: This file is auto-generated by openapi-generator during `make generate`.
# Once you add real test implementations, protect this file from being overwritten
# by adding it to .openapi-generator-ignore:
#
#     test/test_pay_grades_bands_api.py
#
# See README.md for details on protecting implemented tests.


class TestPayGradesBandsApi(unittest.TestCase):
    """PayGradesBandsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PayGradesBandsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_compensation_level_groups_or_level(self) -> None:
        """Test case for delete_compensation_level_groups_or_level

        Delete Compensation Level Groups or Level
        """
        pass

    def test_get_compensation_level_group_status_counts(self) -> None:
        """Test case for get_compensation_level_group_status_counts

        Get Compensation Level Group Status Counts
        """
        pass

    def test_get_job_title_level_assignments(self) -> None:
        """Test case for get_job_title_level_assignments

        Get Job Titles and Level Assignments
        """
        pass

    def test_get_levels_and_bands_review(self) -> None:
        """Test case for get_levels_and_bands_review

        Get Levels and Bands Review
        """
        pass

    def test_get_levels_and_bands_status(self) -> None:
        """Test case for get_levels_and_bands_status

        Get Levels and Bands Status
        """
        pass

    def test_get_pay_bands(self) -> None:
        """Test case for get_pay_bands

        Get Pay Bands
        """
        pass

    def test_get_published_levels_and_bands(self) -> None:
        """Test case for get_published_levels_and_bands

        Get Published Levels and Bands
        """
        pass

    def test_list_compensation_level_groups_and_levels(self) -> None:
        """Test case for list_compensation_level_groups_and_levels

        List Compensation Level Groups and Levels
        """
        pass

    def test_list_job_titles_with_employees(self) -> None:
        """Test case for list_job_titles_with_employees

        List Job Titles with Employees
        """
        pass

    def test_publish_draft_compensation_level_groups(self) -> None:
        """Test case for publish_draft_compensation_level_groups

        Publish Draft Compensation Level Groups
        """
        pass

    def test_replace_job_title_level_assignments(self) -> None:
        """Test case for replace_job_title_level_assignments

        Replace Job Title Level Assignments
        """
        pass

    def test_update_compensation_level_groups_and_levels(self) -> None:
        """Test case for update_compensation_level_groups_and_levels

        Update Compensation Level Groups and Levels
        """
        pass

    def test_update_pay_bands(self) -> None:
        """Test case for update_pay_bands

        Update Pay Bands
        """
        pass

    def test_upload_levels_and_bands_csv(self) -> None:
        """Test case for upload_levels_and_bands_csv

        Upload Levels and Bands CSV
        """
        pass


if __name__ == '__main__':
    unittest.main()
