# coding: utf-8

"""
    BambooHR API

    BambooHR API documentation. https://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bamboohr_sdk.api.reports_api import ReportsApi


# WARNING: This file is auto-generated by openapi-generator during `make generate`.
# Once you add real test implementations, protect this file from being overwritten
# by adding it to .openapi-generator-ignore:
#
#     test/test_reports_api.py
#
# See README.md for details on protecting implemented tests.


class TestReportsApi(unittest.TestCase):
    """ReportsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReportsApi()

    def tearDown(self) -> None:
        pass

    def test_get_company_report(self) -> None:
        """Test case for get_company_report

        Get Company Report
        """
        pass

    def test_request_custom_report(self) -> None:
        """Test case for request_custom_report

        Request Custom Report
        """
        pass


if __name__ == '__main__':
    unittest.main()
