# coding: utf-8

"""
    BambooHR API

    BambooHR API documentation. https://documentation.bamboohr.com/

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bamboohr_sdk.api.employee_tables_api import EmployeeTablesApi


# WARNING: This file is auto-generated by openapi-generator during `make generate`.
# Once you add real test implementations, protect this file from being overwritten
# by adding it to .openapi-generator-ignore:
#
#     test/test_employee_tables_api.py
#
# See README.md for details on protecting implemented tests.


class TestEmployeeTablesApi(unittest.TestCase):
    """EmployeeTablesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmployeeTablesApi()

    def tearDown(self) -> None:
        pass

    def test_create_table_row_v1(self) -> None:
        """Test case for create_table_row_v1

        Create Table Row (v1)
        """
        pass

    def test_create_table_row_v11(self) -> None:
        """Test case for create_table_row_v11

        Create Table Row (v1.1)
        """
        pass

    def test_delete_employee_table_row(self) -> None:
        """Test case for delete_employee_table_row

        Delete Employee Table Row
        """
        pass

    def test_get_employee_table_data(self) -> None:
        """Test case for get_employee_table_data

        Get Employee Table Data
        """
        pass

    def test_update_table_row_v1(self) -> None:
        """Test case for update_table_row_v1

        Update Table Row (v1)
        """
        pass

    def test_update_table_row_v11(self) -> None:
        """Test case for update_table_row_v11

        Update Table Row (v1.1)
        """
        pass


if __name__ == '__main__':
    unittest.main()
