# coding: utf-8

"""
    BambooHR API

    BambooHR API documentation. https://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bamboohr_sdk.api.time_off_api import TimeOffApi


# WARNING: This file is auto-generated by openapi-generator during `make generate`.
# Once you add real test implementations, protect this file from being overwritten
# by adding it to .openapi-generator-ignore:
#
#     test/test_time_off_api.py
#
# See README.md for details on protecting implemented tests.


class TestTimeOffApi(unittest.TestCase):
    """TimeOffApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TimeOffApi()

    def tearDown(self) -> None:
        pass

    def test_get_a_list_of_who_is_out(self) -> None:
        """Test case for get_a_list_of_who_is_out

        Get Who’s Out
        """
        pass

    def test_get_time_off_policies(self) -> None:
        """Test case for get_time_off_policies

        Get Time Off Policies
        """
        pass

    def test_get_time_off_types(self) -> None:
        """Test case for get_time_off_types

        Get Time Off Types
        """
        pass

    def test_time_off_add_a_time_off_history_item_for_time_off_request(self) -> None:
        """Test case for time_off_add_a_time_off_history_item_for_time_off_request

        Create Time Off Request History Item
        """
        pass

    def test_time_off_add_a_time_off_request(self) -> None:
        """Test case for time_off_add_a_time_off_request

        Create Time Off Request
        """
        pass

    def test_time_off_adjust_time_off_balance(self) -> None:
        """Test case for time_off_adjust_time_off_balance

        Update Time Off Balance
        """
        pass

    def test_time_off_assign_time_off_policies_for_an_employee(self) -> None:
        """Test case for time_off_assign_time_off_policies_for_an_employee

        Assign Time Off Policies
        """
        pass

    def test_time_off_assign_time_off_policies_for_an_employee_v1_1(self) -> None:
        """Test case for time_off_assign_time_off_policies_for_an_employee_v1_1

        Assign Time Off Policies v1.1
        """
        pass

    def test_time_off_change_a_request_status(self) -> None:
        """Test case for time_off_change_a_request_status

        Update Time Off Request Status
        """
        pass

    def test_time_off_get_time_off_balance(self) -> None:
        """Test case for time_off_get_time_off_balance

        Get Time Off Balance
        """
        pass

    def test_time_off_get_time_off_requests(self) -> None:
        """Test case for time_off_get_time_off_requests

        Get Time Off Requests
        """
        pass

    def test_time_off_list_time_off_policies_for_employee(self) -> None:
        """Test case for time_off_list_time_off_policies_for_employee

        Get Time Off Policies for Employee
        """
        pass

    def test_time_off_list_time_off_policies_for_employee_v1_1(self) -> None:
        """Test case for time_off_list_time_off_policies_for_employee_v1_1

        Get Time Off Policies for Employee v1.1
        """
        pass


if __name__ == '__main__':
    unittest.main()
