"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Self

from bamboohr_sdk.models.levels_and_bands_pay_band import LevelsAndBandsPayBand


class Ad7871529b2a9c6612f8dd3c62192c08Request(BaseModel):
    """
    Ad7871529b2a9c6612f8dd3c62192c08Request
    """

    pay_band_type: StrictStr = Field(alias="payBandType")
    pay_bands: list[LevelsAndBandsPayBand] = Field(alias="payBands")
    __properties: ClassVar[list[str]] = ["payBandType", "payBands"]

    @field_validator("pay_band_type")
    def pay_band_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["percentRange", "minMidMax"]):
            raise ValueError("must be one of enum values ('percentRange', 'minMidMax')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of Ad7871529b2a9c6612f8dd3c62192c08Request from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in pay_bands (list)
        _items = []
        if self.pay_bands:
            for _item_pay_bands in self.pay_bands:
                if _item_pay_bands:
                    _items.append(_item_pay_bands.to_dict())
            _dict["payBands"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of Ad7871529b2a9c6612f8dd3c62192c08Request from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "payBandType": obj.get("payBandType"),
                "payBands": [LevelsAndBandsPayBand.from_dict(_item) for _item in obj["payBands"]]
                if obj.get("payBands") is not None
                else None,
            }
        )
        return _obj
