
"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing_extensions import Self

from bamboohr_sdk.models.add_training_type_request_category import AddTrainingTypeRequestCategory


class AddTrainingTypeRequest(BaseModel):
    """
    AddTrainingTypeRequest
    """

    name: StrictStr = Field(description="Name of the new training type.")
    frequency: StrictInt | None = Field(
        default=None,
        description="The frequency is the (optional) amount of months between renewing trainings. Not valid if training are not renewable.",
    )
    renewable: StrictBool | None = Field(
        default=None,
        description="Renewable is optional but if you are setting it to true you must pass a frequency which is the months between renewals.",
    )
    category: AddTrainingTypeRequestCategory | None = None
    required: StrictBool = Field(description="Is this a required training?")
    due_from_hire_date: StrictInt | None = Field(
        default=None,
        description="Number of days before the training is due for new hires. Not valid unless training is required.",
        alias="dueFromHireDate",
    )
    link_url: StrictStr | None = Field(
        default=None, description="Optional URL that can be included with a training.", alias="linkUrl"
    )
    description: StrictStr | None = Field(default=None, description="Description for the training.")
    allow_employees_to_mark_complete: StrictBool | None = Field(
        default=None,
        description="Allows all employees who can view the training to be able to mark it complete.",
        alias="allowEmployeesToMarkComplete",
    )
    __properties: ClassVar[list[str]] = [
        "name",
        "frequency",
        "renewable",
        "category",
        "required",
        "dueFromHireDate",
        "linkUrl",
        "description",
        "allowEmployeesToMarkComplete",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of AddTrainingTypeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of category
        if self.category:
            _dict["category"] = self.category.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of AddTrainingTypeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "frequency": obj.get("frequency"),
                "renewable": obj.get("renewable"),
                "category": AddTrainingTypeRequestCategory.from_dict(obj["category"])
                if obj.get("category") is not None
                else None,
                "required": obj.get("required"),
                "dueFromHireDate": obj.get("dueFromHireDate"),
                "linkUrl": obj.get("linkUrl"),
                "description": obj.get("description"),
                "allowEmployeesToMarkComplete": obj.get("allowEmployeesToMarkComplete"),
            }
        )
        return _obj
