
"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing_extensions import Self


class AdjustTimeTrackingRequestSchema(BaseModel):
    """
    Schema for adjust time tracking request body
    """

    time_tracking_id: StrictStr = Field(
        description="The time tracking id is the id that was used to track the record up to 36 characters in length. (i.e. UUID).",
        alias="timeTrackingId",
    )
    hours_worked: StrictFloat | StrictInt = Field(
        description="The updated number of hours worked. e.g. if Employee A worked 8.0 hours originally and decided they only worked 6.0, please send 6.0 here not -2.0.",
        alias="hoursWorked",
    )
    project_id: StrictInt | None = Field(
        default=None, description="ID of the project associated with this time tracking record", alias="projectId"
    )
    task_id: StrictInt | None = Field(
        default=None, description="ID of the task associated with this time tracking record", alias="taskId"
    )
    shift_differential_id: StrictInt | None = Field(
        default=None,
        description="ID of the shift differential associated with this time tracking record",
        alias="shiftDifferentialId",
    )
    holiday_id: StrictInt | None = Field(
        default=None, description="ID of the holiday associated with this time tracking record", alias="holidayId"
    )
    __properties: ClassVar[list[str]] = [
        "timeTrackingId",
        "hoursWorked",
        "projectId",
        "taskId",
        "shiftDifferentialId",
        "holidayId",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of AdjustTimeTrackingRequestSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if project_id (nullable) is None
        # and model_fields_set contains the field
        if self.project_id is None and "project_id" in self.model_fields_set:
            _dict["projectId"] = None

        # set to None if task_id (nullable) is None
        # and model_fields_set contains the field
        if self.task_id is None and "task_id" in self.model_fields_set:
            _dict["taskId"] = None

        # set to None if shift_differential_id (nullable) is None
        # and model_fields_set contains the field
        if self.shift_differential_id is None and "shift_differential_id" in self.model_fields_set:
            _dict["shiftDifferentialId"] = None

        # set to None if holiday_id (nullable) is None
        # and model_fields_set contains the field
        if self.holiday_id is None and "holiday_id" in self.model_fields_set:
            _dict["holidayId"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of AdjustTimeTrackingRequestSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "timeTrackingId": obj.get("timeTrackingId"),
                "hoursWorked": obj.get("hoursWorked"),
                "projectId": obj.get("projectId"),
                "taskId": obj.get("taskId"),
                "shiftDifferentialId": obj.get("shiftDifferentialId"),
                "holidayId": obj.get("holidayId"),
            }
        )
        return _obj
