"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Self


class ApplicationDetailsApplicant(BaseModel):
    """
    Information about the applicant
    """

    id: StrictInt | None = Field(default=None, description="Applicant ID")
    first_name: StrictStr | None = Field(default=None, description="First name", alias="firstName")
    last_name: StrictStr | None = Field(default=None, description="Last name", alias="lastName")
    email: StrictStr | None = Field(default=None, description="Email address")
    phone_number: StrictStr | None = Field(default=None, alias="phoneNumber")
    avatar: StrictStr | None = None
    source: StrictStr | None = None
    twitter_username: StrictStr | None = Field(default=None, alias="twitterUsername")
    address: dict[str, Any] | None = None
    linkedin_url: StrictStr | None = Field(default=None, alias="linkedinUrl")
    website_url: StrictStr | None = Field(default=None, alias="websiteUrl")
    available_start_date: date | None = Field(default=None, alias="availableStartDate")
    education: dict[str, Any] | None = None
    __properties: ClassVar[list[str]] = [
        "id",
        "firstName",
        "lastName",
        "email",
        "phoneNumber",
        "avatar",
        "source",
        "twitterUsername",
        "address",
        "linkedinUrl",
        "websiteUrl",
        "availableStartDate",
        "education",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ApplicationDetailsApplicant from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if phone_number (nullable) is None
        # and model_fields_set contains the field
        if self.phone_number is None and "phone_number" in self.model_fields_set:
            _dict["phoneNumber"] = None

        # set to None if avatar (nullable) is None
        # and model_fields_set contains the field
        if self.avatar is None and "avatar" in self.model_fields_set:
            _dict["avatar"] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict["source"] = None

        # set to None if twitter_username (nullable) is None
        # and model_fields_set contains the field
        if self.twitter_username is None and "twitter_username" in self.model_fields_set:
            _dict["twitterUsername"] = None

        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict["address"] = None

        # set to None if linkedin_url (nullable) is None
        # and model_fields_set contains the field
        if self.linkedin_url is None and "linkedin_url" in self.model_fields_set:
            _dict["linkedinUrl"] = None

        # set to None if website_url (nullable) is None
        # and model_fields_set contains the field
        if self.website_url is None and "website_url" in self.model_fields_set:
            _dict["websiteUrl"] = None

        # set to None if available_start_date (nullable) is None
        # and model_fields_set contains the field
        if self.available_start_date is None and "available_start_date" in self.model_fields_set:
            _dict["availableStartDate"] = None

        # set to None if education (nullable) is None
        # and model_fields_set contains the field
        if self.education is None and "education" in self.model_fields_set:
            _dict["education"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ApplicationDetailsApplicant from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "firstName": obj.get("firstName"),
                "lastName": obj.get("lastName"),
                "email": obj.get("email"),
                "phoneNumber": obj.get("phoneNumber"),
                "avatar": obj.get("avatar"),
                "source": obj.get("source"),
                "twitterUsername": obj.get("twitterUsername"),
                "address": obj.get("address"),
                "linkedinUrl": obj.get("linkedinUrl"),
                "websiteUrl": obj.get("websiteUrl"),
                "availableStartDate": obj.get("availableStartDate"),
                "education": obj.get("education"),
            }
        )
        return _obj
