"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Self

from bamboohr_sdk.models.application_details_applicant import ApplicationDetailsApplicant
from bamboohr_sdk.models.application_details_attachments_inner import ApplicationDetailsAttachmentsInner
from bamboohr_sdk.models.application_details_job import ApplicationDetailsJob
from bamboohr_sdk.models.application_details_questions_and_answers_inner import (
    ApplicationDetailsQuestionsAndAnswersInner,
)
from bamboohr_sdk.models.application_details_status import ApplicationDetailsStatus


class ApplicationDetails(BaseModel):
    """
    ApplicationDetails
    """

    id: StrictInt | None = Field(default=None, description="Application ID")
    applied_date: datetime | None = Field(
        default=None, description="ISO 8601 datetime when the application was submitted", alias="appliedDate"
    )
    status: ApplicationDetailsStatus | None = None
    rating: StrictInt | None = None
    resume_file_id: StrictInt | None = Field(default=None, alias="resumeFileId")
    cover_letter_file_id: StrictInt | None = Field(default=None, alias="coverLetterFileId")
    attachment_count: StrictInt | None = Field(default=None, alias="attachmentCount")
    attachments: list[ApplicationDetailsAttachmentsInner] | None = None
    moved_to: list[dict[str, Any]] | None = Field(default=None, alias="movedTo")
    moved_from: list[dict[str, Any]] | None = Field(default=None, alias="movedFrom")
    also_considered_for_count: StrictInt | None = Field(
        default=None,
        description="Count of other job openings this applicant is also being considered for",
        alias="alsoConsideredForCount",
    )
    duplicate_application_count: StrictInt | None = Field(
        default=None,
        description="Count of duplicate applications from this applicant",
        alias="duplicateApplicationCount",
    )
    referred_by: StrictStr | None = Field(default=None, alias="referredBy")
    desired_salary: StrictStr | None = Field(default=None, alias="desiredSalary")
    comment_count: StrictInt | None = Field(
        default=None, description="Number of comments on this application", alias="commentCount"
    )
    email_count: StrictInt | None = Field(
        default=None, description="Number of emails sent for this application", alias="emailCount"
    )
    event_count: StrictInt | None = Field(
        default=None, description="Number of events associated with this application", alias="eventCount"
    )
    questions_and_answers: list[ApplicationDetailsQuestionsAndAnswersInner] | None = Field(
        default=None,
        description="List of custom application questions and the applicant's answers",
        alias="questionsAndAnswers",
    )
    application_references: StrictStr | None = Field(default=None, alias="applicationReferences")
    applicant: ApplicationDetailsApplicant | None = None
    job: ApplicationDetailsJob | None = None
    __properties: ClassVar[list[str]] = [
        "id",
        "appliedDate",
        "status",
        "rating",
        "resumeFileId",
        "coverLetterFileId",
        "attachmentCount",
        "attachments",
        "movedTo",
        "movedFrom",
        "alsoConsideredForCount",
        "duplicateApplicationCount",
        "referredBy",
        "desiredSalary",
        "commentCount",
        "emailCount",
        "eventCount",
        "questionsAndAnswers",
        "applicationReferences",
        "applicant",
        "job",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ApplicationDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of status
        if self.status:
            _dict["status"] = self.status.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item_attachments in self.attachments:
                if _item_attachments:
                    _items.append(_item_attachments.to_dict())
            _dict["attachments"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in questions_and_answers (list)
        _items = []
        if self.questions_and_answers:
            for _item_questions_and_answers in self.questions_and_answers:
                if _item_questions_and_answers:
                    _items.append(_item_questions_and_answers.to_dict())
            _dict["questionsAndAnswers"] = _items
        # override the default output from pydantic by calling `to_dict()` of applicant
        if self.applicant:
            _dict["applicant"] = self.applicant.to_dict()
        # override the default output from pydantic by calling `to_dict()` of job
        if self.job:
            _dict["job"] = self.job.to_dict()
        # set to None if rating (nullable) is None
        # and model_fields_set contains the field
        if self.rating is None and "rating" in self.model_fields_set:
            _dict["rating"] = None

        # set to None if resume_file_id (nullable) is None
        # and model_fields_set contains the field
        if self.resume_file_id is None and "resume_file_id" in self.model_fields_set:
            _dict["resumeFileId"] = None

        # set to None if cover_letter_file_id (nullable) is None
        # and model_fields_set contains the field
        if self.cover_letter_file_id is None and "cover_letter_file_id" in self.model_fields_set:
            _dict["coverLetterFileId"] = None

        # set to None if attachment_count (nullable) is None
        # and model_fields_set contains the field
        if self.attachment_count is None and "attachment_count" in self.model_fields_set:
            _dict["attachmentCount"] = None

        # set to None if attachments (nullable) is None
        # and model_fields_set contains the field
        if self.attachments is None and "attachments" in self.model_fields_set:
            _dict["attachments"] = None

        # set to None if moved_to (nullable) is None
        # and model_fields_set contains the field
        if self.moved_to is None and "moved_to" in self.model_fields_set:
            _dict["movedTo"] = None

        # set to None if moved_from (nullable) is None
        # and model_fields_set contains the field
        if self.moved_from is None and "moved_from" in self.model_fields_set:
            _dict["movedFrom"] = None

        # set to None if referred_by (nullable) is None
        # and model_fields_set contains the field
        if self.referred_by is None and "referred_by" in self.model_fields_set:
            _dict["referredBy"] = None

        # set to None if desired_salary (nullable) is None
        # and model_fields_set contains the field
        if self.desired_salary is None and "desired_salary" in self.model_fields_set:
            _dict["desiredSalary"] = None

        # set to None if application_references (nullable) is None
        # and model_fields_set contains the field
        if self.application_references is None and "application_references" in self.model_fields_set:
            _dict["applicationReferences"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ApplicationDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "appliedDate": obj.get("appliedDate"),
                "status": ApplicationDetailsStatus.from_dict(obj["status"]) if obj.get("status") is not None else None,
                "rating": obj.get("rating"),
                "resumeFileId": obj.get("resumeFileId"),
                "coverLetterFileId": obj.get("coverLetterFileId"),
                "attachmentCount": obj.get("attachmentCount"),
                "attachments": [ApplicationDetailsAttachmentsInner.from_dict(_item) for _item in obj["attachments"]]
                if obj.get("attachments") is not None
                else None,
                "movedTo": obj.get("movedTo"),
                "movedFrom": obj.get("movedFrom"),
                "alsoConsideredForCount": obj.get("alsoConsideredForCount"),
                "duplicateApplicationCount": obj.get("duplicateApplicationCount"),
                "referredBy": obj.get("referredBy"),
                "desiredSalary": obj.get("desiredSalary"),
                "commentCount": obj.get("commentCount"),
                "emailCount": obj.get("emailCount"),
                "eventCount": obj.get("eventCount"),
                "questionsAndAnswers": [
                    ApplicationDetailsQuestionsAndAnswersInner.from_dict(_item) for _item in obj["questionsAndAnswers"]
                ]
                if obj.get("questionsAndAnswers") is not None
                else None,
                "applicationReferences": obj.get("applicationReferences"),
                "applicant": ApplicationDetailsApplicant.from_dict(obj["applicant"])
                if obj.get("applicant") is not None
                else None,
                "job": ApplicationDetailsJob.from_dict(obj["job"]) if obj.get("job") is not None else None,
            }
        )
        return _obj
