"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing_extensions import Self

from bamboohr_sdk.models.benefit_deduction_sub_type import BenefitDeductionSubType
from bamboohr_sdk.models.benefit_deduction_type_id import BenefitDeductionTypeId


class BenefitDeductionType(BaseModel):
    """
    BenefitDeductionType
    """

    id: BenefitDeductionTypeId | None = None
    deduction_type_name: StrictStr | None = Field(
        default=None, description="The display name of the deduction type.", alias="deductionTypeName"
    )
    default_deduction_code: StrictStr | None = Field(
        default=None, description="The default payroll deduction code for this type.", alias="defaultDeductionCode"
    )
    allowable_benefit_types: list[StrictStr | None] | None = Field(
        default=None,
        description='The benefit plan types this deduction type can be applied to (e.g. "health", "dental", "retirement").',
        alias="allowableBenefitTypes",
    )
    non_benefit_deduction_type: StrictBool | None = Field(
        default=None,
        description="Whether this is a non-benefit deduction type (e.g. garnishments).",
        alias="nonBenefitDeductionType",
    )
    can_be_collected_by_trax: StrictBool | None = Field(
        default=None,
        description="Whether this deduction type can be collected via Trax Payroll.",
        alias="canBeCollectedByTrax",
    )
    additional_description: StrictStr | None = Field(
        default=None,
        description="An optional additional description for display purposes.",
        alias="additionalDescription",
    )
    hide_annual_max: StrictBool | None = Field(
        default=None,
        description="Whether the annual maximum field should be hidden for this deduction type.",
        alias="hideAnnualMax",
    )
    managed_deduction_type: StrictStr | None = Field(default=None, alias="managedDeductionType")
    sub_types: list[BenefitDeductionSubType] | None = Field(
        default=None,
        description="Child deduction types grouped under this parent. Each entry has the same shape as a top-level deduction type. Empty array if this type has no sub-types.",
        alias="subTypes",
    )
    sub_type_text: StrictStr | None = Field(
        default=None,
        description='A label or question displayed alongside sub-type selection (e.g. "Reportable on the W-2?"). Empty string for types without sub-types.',
        alias="subTypeText",
    )
    deduction_note: StrictStr | None = Field(
        default=None,
        description="An informational note to display to the user when configuring this deduction type.",
        alias="deductionNote",
    )
    deduction_note_link: StrictStr | None = Field(
        default=None,
        description='A URL for a "learn more" link associated with the deduction note.',
        alias="deductionNoteLink",
    )
    deduction_note_link_text: StrictStr | None = Field(
        default=None, description="The display text for the deduction note link.", alias="deductionNoteLinkText"
    )
    __properties: ClassVar[list[str]] = [
        "id",
        "deductionTypeName",
        "defaultDeductionCode",
        "allowableBenefitTypes",
        "nonBenefitDeductionType",
        "canBeCollectedByTrax",
        "additionalDescription",
        "hideAnnualMax",
        "managedDeductionType",
        "subTypes",
        "subTypeText",
        "deductionNote",
        "deductionNoteLink",
        "deductionNoteLinkText",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of BenefitDeductionType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of id
        if self.id:
            _dict["id"] = self.id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in sub_types (list)
        _items = []
        if self.sub_types:
            for _item_sub_types in self.sub_types:
                if _item_sub_types:
                    _items.append(_item_sub_types.to_dict())
            _dict["subTypes"] = _items
        # set to None if managed_deduction_type (nullable) is None
        # and model_fields_set contains the field
        if self.managed_deduction_type is None and "managed_deduction_type" in self.model_fields_set:
            _dict["managedDeductionType"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of BenefitDeductionType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": BenefitDeductionTypeId.from_dict(obj["id"]) if obj.get("id") is not None else None,
                "deductionTypeName": obj.get("deductionTypeName"),
                "defaultDeductionCode": obj.get("defaultDeductionCode"),
                "allowableBenefitTypes": obj.get("allowableBenefitTypes"),
                "nonBenefitDeductionType": obj.get("nonBenefitDeductionType"),
                "canBeCollectedByTrax": obj.get("canBeCollectedByTrax"),
                "additionalDescription": obj.get("additionalDescription"),
                "hideAnnualMax": obj.get("hideAnnualMax"),
                "managedDeductionType": obj.get("managedDeductionType"),
                "subTypes": [BenefitDeductionSubType.from_dict(_item) for _item in obj["subTypes"]]
                if obj.get("subTypes") is not None
                else None,
                "subTypeText": obj.get("subTypeText"),
                "deductionNote": obj.get("deductionNote"),
                "deductionNoteLink": obj.get("deductionNoteLink"),
                "deductionNoteLinkText": obj.get("deductionNoteLinkText"),
            }
        )
        return _obj
