# coding: utf-8

"""
    BambooHR API

    BambooHR API documentation. https://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class BenefitDeductionSubType(BaseModel):
    """
    BenefitDeductionSubType
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The sub-type deduction type ID (always an integer).")
    deduction_type_name: Optional[StrictStr] = Field(default=None, description="The display name of the sub-type.", alias="deductionTypeName")
    default_deduction_code: Optional[StrictStr] = Field(default=None, description="The default payroll deduction code for this sub-type.", alias="defaultDeductionCode")
    allowable_benefit_types: Optional[List[StrictStr]] = Field(default=None, description="Benefit plan types this sub-type applies to.", alias="allowableBenefitTypes")
    non_benefit_deduction_type: Optional[StrictBool] = Field(default=None, description="Whether this is a non-benefit deduction type.", alias="nonBenefitDeductionType")
    can_be_collected_by_trax: Optional[StrictBool] = Field(default=None, description="Whether this sub-type can be collected via Trax Payroll.", alias="canBeCollectedByTrax")
    additional_description: Optional[StrictStr] = Field(default=None, description="Additional description for display purposes.", alias="additionalDescription")
    hide_annual_max: Optional[StrictBool] = Field(default=None, description="Whether the annual maximum field should be hidden.", alias="hideAnnualMax")
    managed_deduction_type: Optional[StrictStr] = Field(default=None, description="The managed deduction type identifier, if applicable. Null if not managed.", alias="managedDeductionType")
    sub_types: Optional[List[Dict[str, Any]]] = Field(default=None, description="Always an empty array for sub-types.", alias="subTypes")
    sub_type_text: Optional[StrictStr] = Field(default=None, description="Sub-type selection label. Empty string for leaf types.", alias="subTypeText")
    deduction_note: Optional[StrictStr] = Field(default=None, description="Informational note for this sub-type.", alias="deductionNote")
    deduction_note_link: Optional[StrictStr] = Field(default=None, description="URL for the deduction note link.", alias="deductionNoteLink")
    deduction_note_link_text: Optional[StrictStr] = Field(default=None, description="Display text for the deduction note link.", alias="deductionNoteLinkText")
    __properties: ClassVar[List[str]] = ["id", "deductionTypeName", "defaultDeductionCode", "allowableBenefitTypes", "nonBenefitDeductionType", "canBeCollectedByTrax", "additionalDescription", "hideAnnualMax", "managedDeductionType", "subTypes", "subTypeText", "deductionNote", "deductionNoteLink", "deductionNoteLinkText"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BenefitDeductionSubType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if managed_deduction_type (nullable) is None
        # and model_fields_set contains the field
        if self.managed_deduction_type is None and "managed_deduction_type" in self.model_fields_set:
            _dict['managedDeductionType'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BenefitDeductionSubType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "deductionTypeName": obj.get("deductionTypeName"),
            "defaultDeductionCode": obj.get("defaultDeductionCode"),
            "allowableBenefitTypes": obj.get("allowableBenefitTypes"),
            "nonBenefitDeductionType": obj.get("nonBenefitDeductionType"),
            "canBeCollectedByTrax": obj.get("canBeCollectedByTrax"),
            "additionalDescription": obj.get("additionalDescription"),
            "hideAnnualMax": obj.get("hideAnnualMax"),
            "managedDeductionType": obj.get("managedDeductionType"),
            "subTypes": obj.get("subTypes"),
            "subTypeText": obj.get("subTypeText"),
            "deductionNote": obj.get("deductionNote"),
            "deductionNoteLink": obj.get("deductionNoteLink"),
            "deductionNoteLinkText": obj.get("deductionNoteLinkText")
        })
        return _obj


