"""
BambooHR API

BambooHR API documentation. https://documentation.bamboohr.com/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Self

from bamboohr_sdk.models.clock_entry_clock_entry_location_input_v1 import ClockEntryClockEntryLocationInputV1


class ClockEntryCreateClockEntryV1(BaseModel):
    """
    Request body for manually creating a time tracking clock entry (corrections, retroactive entry). `timesheetId` and `date` are derived server-side from `start` + `timezone`.
    """

    employee_id: StrictInt = Field(description="The employee the clock entry belongs to.", alias="employeeId")
    start: datetime = Field(description="Clock-in timestamp (ISO 8601).")
    end: datetime = Field(description="Clock-out timestamp (ISO 8601). Must be after start.")
    timezone: StrictStr = Field(description="IANA timezone identifier the times are recorded under.")
    note: StrictStr | None = None
    project_id: StrictInt | None = Field(default=None, alias="projectId")
    task_id: StrictInt | None = Field(default=None, alias="taskId")
    clock_in_location: ClockEntryClockEntryLocationInputV1 | None = Field(
        default=None, description="Geolocation captured at clock-in.", alias="clockInLocation"
    )
    clock_out_location: ClockEntryClockEntryLocationInputV1 | None = Field(
        default=None, description="Geolocation captured at clock-out.", alias="clockOutLocation"
    )
    __properties: ClassVar[list[str]] = [
        "employeeId",
        "start",
        "end",
        "timezone",
        "note",
        "projectId",
        "taskId",
        "clockInLocation",
        "clockOutLocation",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ClockEntryCreateClockEntryV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of clock_in_location
        if self.clock_in_location:
            _dict["clockInLocation"] = self.clock_in_location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of clock_out_location
        if self.clock_out_location:
            _dict["clockOutLocation"] = self.clock_out_location.to_dict()
        # set to None if note (nullable) is None
        # and model_fields_set contains the field
        if self.note is None and "note" in self.model_fields_set:
            _dict["note"] = None

        # set to None if project_id (nullable) is None
        # and model_fields_set contains the field
        if self.project_id is None and "project_id" in self.model_fields_set:
            _dict["projectId"] = None

        # set to None if task_id (nullable) is None
        # and model_fields_set contains the field
        if self.task_id is None and "task_id" in self.model_fields_set:
            _dict["taskId"] = None

        # set to None if clock_in_location (nullable) is None
        # and model_fields_set contains the field
        if self.clock_in_location is None and "clock_in_location" in self.model_fields_set:
            _dict["clockInLocation"] = None

        # set to None if clock_out_location (nullable) is None
        # and model_fields_set contains the field
        if self.clock_out_location is None and "clock_out_location" in self.model_fields_set:
            _dict["clockOutLocation"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ClockEntryCreateClockEntryV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "employeeId": obj.get("employeeId"),
                "start": obj.get("start"),
                "end": obj.get("end"),
                "timezone": obj.get("timezone"),
                "note": obj.get("note"),
                "projectId": obj.get("projectId"),
                "taskId": obj.get("taskId"),
                "clockInLocation": ClockEntryClockEntryLocationInputV1.from_dict(obj["clockInLocation"])
                if obj.get("clockInLocation") is not None
                else None,
                "clockOutLocation": ClockEntryClockEntryLocationInputV1.from_dict(obj["clockOutLocation"])
                if obj.get("clockOutLocation") is not None
                else None,
            }
        )
        return _obj
