"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Self

from bamboohr_sdk.models.company_profile_data_address import CompanyProfileDataAddress


class CompanyProfileData(BaseModel):
    """
    CompanyProfileData
    """

    id: StrictInt | None = None
    subdomain: StrictStr | None = None
    legal_name: StrictStr | None = Field(default=None, alias="legalName")
    display_name: StrictStr | None = Field(default=None, alias="displayName")
    address: CompanyProfileDataAddress | None = None
    phone: StrictStr | None = None
    status: StrictStr | None = None
    termination_date: StrictStr | None = Field(default=None, alias="terminationDate")
    industry_code: StrictStr | None = Field(default=None, alias="industryCode")
    __properties: ClassVar[list[str]] = [
        "id",
        "subdomain",
        "legalName",
        "displayName",
        "address",
        "phone",
        "status",
        "terminationDate",
        "industryCode",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of CompanyProfileData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict["address"] = self.address.to_dict()
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict["id"] = None

        # set to None if subdomain (nullable) is None
        # and model_fields_set contains the field
        if self.subdomain is None and "subdomain" in self.model_fields_set:
            _dict["subdomain"] = None

        # set to None if legal_name (nullable) is None
        # and model_fields_set contains the field
        if self.legal_name is None and "legal_name" in self.model_fields_set:
            _dict["legalName"] = None

        # set to None if display_name (nullable) is None
        # and model_fields_set contains the field
        if self.display_name is None and "display_name" in self.model_fields_set:
            _dict["displayName"] = None

        # set to None if phone (nullable) is None
        # and model_fields_set contains the field
        if self.phone is None and "phone" in self.model_fields_set:
            _dict["phone"] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict["status"] = None

        # set to None if termination_date (nullable) is None
        # and model_fields_set contains the field
        if self.termination_date is None and "termination_date" in self.model_fields_set:
            _dict["terminationDate"] = None

        # set to None if industry_code (nullable) is None
        # and model_fields_set contains the field
        if self.industry_code is None and "industry_code" in self.model_fields_set:
            _dict["industryCode"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of CompanyProfileData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "subdomain": obj.get("subdomain"),
                "legalName": obj.get("legalName"),
                "displayName": obj.get("displayName"),
                "address": CompanyProfileDataAddress.from_dict(obj["address"])
                if obj.get("address") is not None
                else None,
                "phone": obj.get("phone"),
                "status": obj.get("status"),
                "terminationDate": obj.get("terminationDate"),
                "industryCode": obj.get("industryCode"),
            }
        )
        return _obj
