# coding: utf-8

"""
    BambooHR API

    BambooHR API documentation. https://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CompanyBenefitSummary(BaseModel):
    """
    A summary representation of a company benefit plan as returned by the list endpoint.
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the company benefit plan.")
    name: Optional[StrictStr] = Field(default=None, description="The name of the company benefit plan.")
    type: Optional[StrictStr] = Field(default=None, description="The benefit category type.")
    benefit_vendor_id: Optional[StrictStr] = Field(default=None, description="The ID of the benefit vendor associated with this plan, or null if none.", alias="benefitVendorId")
    deduction_type_id: Optional[StrictStr] = Field(default=None, description="The deduction type ID for this plan, or null if not applicable.", alias="deductionTypeId")
    company_deduction_id: Optional[StrictStr] = Field(default=None, description="The company-level deduction record ID linked to this plan, or null if not set.", alias="companyDeductionId")
    start_date: Optional[date] = Field(default=None, description="The date the benefit plan becomes effective (YYYY-MM-DD), or null if not set.", alias="startDate")
    end_date: Optional[date] = Field(default=None, description="The date the benefit plan ends (YYYY-MM-DD), or null if ongoing.", alias="endDate")
    allows_catch_up: Optional[StrictBool] = Field(default=None, description="Whether the plan allows catch-up contributions (e.g., for HSA plans for employees 55+), or null if not applicable to this plan type.", alias="allowsCatchUp")
    allows_super_catch_up: Optional[StrictBool] = Field(default=None, description="Whether the plan allows super catch-up contributions, or null if not applicable to this plan type.", alias="allowsSuperCatchUp")
    __properties: ClassVar[List[str]] = ["id", "name", "type", "benefitVendorId", "deductionTypeId", "companyDeductionId", "startDate", "endDate", "allowsCatchUp", "allowsSuperCatchUp"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['health', 'dental', 'vision', 'retirement', 'hsa', 'flex', 'life', 'disability', 'reimbursement', 'supplemental']):
            raise ValueError("must be one of enum values ('health', 'dental', 'vision', 'retirement', 'hsa', 'flex', 'life', 'disability', 'reimbursement', 'supplemental')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompanyBenefitSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if benefit_vendor_id (nullable) is None
        # and model_fields_set contains the field
        if self.benefit_vendor_id is None and "benefit_vendor_id" in self.model_fields_set:
            _dict['benefitVendorId'] = None

        # set to None if deduction_type_id (nullable) is None
        # and model_fields_set contains the field
        if self.deduction_type_id is None and "deduction_type_id" in self.model_fields_set:
            _dict['deductionTypeId'] = None

        # set to None if company_deduction_id (nullable) is None
        # and model_fields_set contains the field
        if self.company_deduction_id is None and "company_deduction_id" in self.model_fields_set:
            _dict['companyDeductionId'] = None

        # set to None if start_date (nullable) is None
        # and model_fields_set contains the field
        if self.start_date is None and "start_date" in self.model_fields_set:
            _dict['startDate'] = None

        # set to None if end_date (nullable) is None
        # and model_fields_set contains the field
        if self.end_date is None and "end_date" in self.model_fields_set:
            _dict['endDate'] = None

        # set to None if allows_catch_up (nullable) is None
        # and model_fields_set contains the field
        if self.allows_catch_up is None and "allows_catch_up" in self.model_fields_set:
            _dict['allowsCatchUp'] = None

        # set to None if allows_super_catch_up (nullable) is None
        # and model_fields_set contains the field
        if self.allows_super_catch_up is None and "allows_super_catch_up" in self.model_fields_set:
            _dict['allowsSuperCatchUp'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompanyBenefitSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "benefitVendorId": obj.get("benefitVendorId"),
            "deductionTypeId": obj.get("deductionTypeId"),
            "companyDeductionId": obj.get("companyDeductionId"),
            "startDate": obj.get("startDate"),
            "endDate": obj.get("endDate"),
            "allowsCatchUp": obj.get("allowsCatchUp"),
            "allowsSuperCatchUp": obj.get("allowsSuperCatchUp")
        })
        return _obj


