
"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self

from bamboohr_sdk.models.data_request_aggregations_inner import DataRequestAggregationsInner
from bamboohr_sdk.models.data_request_filters import DataRequestFilters
from bamboohr_sdk.models.data_request_sort_by_inner import DataRequestSortByInner


class DataRequest(BaseModel):
    """
    DataRequest
    """

    fields: list[StrictStr]
    aggregations: list[DataRequestAggregationsInner] | None = None
    sort_by: list[DataRequestSortByInner] | None = Field(default=None, alias="sortBy")
    filters: DataRequestFilters | None = None
    group_by: list[StrictStr] | None = Field(default=None, alias="groupBy")
    show_history: list[StrictStr] | None = Field(default=None, alias="showHistory")
    __properties: ClassVar[list[str]] = ["fields", "aggregations", "sortBy", "filters", "groupBy", "showHistory"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of DataRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in aggregations (list)
        _items = []
        if self.aggregations:
            for _item_aggregations in self.aggregations:
                if _item_aggregations:
                    _items.append(_item_aggregations.to_dict())
            _dict["aggregations"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sort_by (list)
        _items = []
        if self.sort_by:
            for _item_sort_by in self.sort_by:
                if _item_sort_by:
                    _items.append(_item_sort_by.to_dict())
            _dict["sortBy"] = _items
        # override the default output from pydantic by calling `to_dict()` of filters
        if self.filters:
            _dict["filters"] = self.filters.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of DataRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "fields": obj.get("fields"),
                "aggregations": [DataRequestAggregationsInner.from_dict(_item) for _item in obj["aggregations"]]
                if obj.get("aggregations") is not None
                else None,
                "sortBy": [DataRequestSortByInner.from_dict(_item) for _item in obj["sortBy"]]
                if obj.get("sortBy") is not None
                else None,
                "filters": DataRequestFilters.from_dict(obj["filters"]) if obj.get("filters") is not None else None,
                "groupBy": obj.get("groupBy"),
                "showHistory": obj.get("showHistory"),
            }
        )
        return _obj
