# coding: utf-8

"""
    BambooHR API

    BambooHR API documentation. https://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from bamboohr_sdk.models.employee_benefits_list_response_employee_benefits_inner_employee_benefit_inner import EmployeeBenefitsListResponseEmployeeBenefitsInnerEmployeeBenefitInner
from typing import Optional, Set
from typing_extensions import Self

class EmployeeBenefitsListResponseEmployeeBenefitsInner(BaseModel):
    """
    EmployeeBenefitsListResponseEmployeeBenefitsInner
    """ # noqa: E501
    employee_id: Optional[StrictInt] = Field(default=None, description="The ID of the employee.", alias="employeeId")
    pay_frequency: Optional[StrictStr] = Field(default=None, description="The employee's current pay frequency (e.g., 'semi-monthly', 'biweekly'), or null if no pay schedule is set.", alias="payFrequency")
    employee_benefit: Optional[List[EmployeeBenefitsListResponseEmployeeBenefitsInnerEmployeeBenefitInner]] = Field(default=None, description="The employee's benefit plan enrollments, including both current and future scheduled changes.", alias="employeeBenefit")
    __properties: ClassVar[List[str]] = ["employeeId", "payFrequency", "employeeBenefit"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EmployeeBenefitsListResponseEmployeeBenefitsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in employee_benefit (list)
        _items = []
        if self.employee_benefit:
            for _item_employee_benefit in self.employee_benefit:
                if _item_employee_benefit:
                    _items.append(_item_employee_benefit.to_dict())
            _dict['employeeBenefit'] = _items
        # set to None if pay_frequency (nullable) is None
        # and model_fields_set contains the field
        if self.pay_frequency is None and "pay_frequency" in self.model_fields_set:
            _dict['payFrequency'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EmployeeBenefitsListResponseEmployeeBenefitsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "employeeId": obj.get("employeeId"),
            "payFrequency": obj.get("payFrequency"),
            "employeeBenefit": [EmployeeBenefitsListResponseEmployeeBenefitsInnerEmployeeBenefitInner.from_dict(_item) for _item in obj["employeeBenefit"]] if obj.get("employeeBenefit") is not None else None
        })
        return _obj


