
"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing_extensions import Self


class GoalAggregateCommentsInner(BaseModel):
    """
    GoalAggregateCommentsInner
    """

    id: StrictInt | None = Field(default=None, description="Id of the comment.")
    author_user_id: StrictInt | None = Field(
        default=None, description="Id of the author of the comment.", alias="authorUserId"
    )
    created_at: StrictStr | None = Field(
        default=None, description="The date and time that the comment was created.", alias="createdAt"
    )
    text: StrictStr | None = Field(default=None, description="The actual text of the comment.")
    can_edit: StrictBool | None = Field(default=None, description="Can the comment be edited.", alias="canEdit")
    can_delete: StrictBool | None = Field(default=None, description="Can the comment be deleted.", alias="canDelete")
    __properties: ClassVar[list[str]] = ["id", "authorUserId", "createdAt", "text", "canEdit", "canDelete"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of GoalAggregateCommentsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of GoalAggregateCommentsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "authorUserId": obj.get("authorUserId"),
                "createdAt": obj.get("createdAt"),
                "text": obj.get("text"),
                "canEdit": obj.get("canEdit"),
                "canDelete": obj.get("canDelete"),
            }
        )
        return _obj
