"""
BambooHR API

BambooHR API documentation. https://documentation.bamboohr.com/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing_extensions import Self

from bamboohr_sdk.models.holiday_bulk_insert_company_holiday_error_v1 import HolidayBulkInsertCompanyHolidayErrorV1
from bamboohr_sdk.models.holiday_bulk_insert_company_holiday_record_v1 import HolidayBulkInsertCompanyHolidayRecordV1


class HolidayBulkInsertCompanyHolidaysResponseV1(BaseModel):
    """
    Result envelope for a synchronous bulk-insert of company holidays.
    """

    status: StrictStr | None = Field(default=None, description="Overall batch outcome")
    operation: StrictStr | None = Field(default=None, description="Operation type for this bulk request")
    total_requested: StrictInt | None = Field(
        default=None, description="Total number of records in the request", alias="totalRequested"
    )
    total_processed: StrictInt | None = Field(
        default=None, description="Total number of records created successfully", alias="totalProcessed"
    )
    failed: StrictInt | None = Field(default=None, description="Total number of records that failed")
    errors: list[HolidayBulkInsertCompanyHolidayErrorV1] | None = Field(
        default=None, description="Per-record problem-details style errors"
    )
    records: list[HolidayBulkInsertCompanyHolidayRecordV1] | None = Field(
        default=None, description="Per-record success results, in request order"
    )
    __properties: ClassVar[list[str]] = [
        "status",
        "operation",
        "totalRequested",
        "totalProcessed",
        "failed",
        "errors",
        "records",
    ]

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["success", "partial_success", "failed"]):
            raise ValueError("must be one of enum values ('success', 'partial_success', 'failed')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of HolidayBulkInsertCompanyHolidaysResponseV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in errors (list)
        _items = []
        if self.errors:
            for _item_errors in self.errors:
                if _item_errors:
                    _items.append(_item_errors.to_dict())
            _dict["errors"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in records (list)
        _items = []
        if self.records:
            for _item_records in self.records:
                if _item_records:
                    _items.append(_item_records.to_dict())
            _dict["records"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of HolidayBulkInsertCompanyHolidaysResponseV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "status": obj.get("status"),
                "operation": obj.get("operation"),
                "totalRequested": obj.get("totalRequested"),
                "totalProcessed": obj.get("totalProcessed"),
                "failed": obj.get("failed"),
                "errors": [HolidayBulkInsertCompanyHolidayErrorV1.from_dict(_item) for _item in obj["errors"]]
                if obj.get("errors") is not None
                else None,
                "records": [HolidayBulkInsertCompanyHolidayRecordV1.from_dict(_item) for _item in obj["records"]]
                if obj.get("records") is not None
                else None,
            }
        )
        return _obj
