"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing_extensions import Self


class LevelsAndBandsPayBand(BaseModel):
    """
    Pay band data object
    """

    level_id: StrictInt | None = Field(default=None, alias="levelId")
    min: StrictFloat | StrictInt | None = Field(default=None, description="The minimum value for the level")
    mid: StrictFloat | StrictInt | None = Field(default=None, description="The middle value for the level")
    max: StrictFloat | StrictInt | None = Field(default=None, description="The maximum value for the level")
    currency_code: StrictStr | None = Field(default=None, alias="currencyCode")
    percentage_range: StrictFloat | StrictInt | None = Field(
        default=None, description="The percentage range for the level", alias="percentageRange"
    )
    compensation_type: StrictStr | None = Field(
        default=None, description="The compensation type for the level", alias="compensationType"
    )
    __properties: ClassVar[list[str]] = [
        "levelId",
        "min",
        "mid",
        "max",
        "currencyCode",
        "percentageRange",
        "compensationType",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of LevelsAndBandsPayBand from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if level_id (nullable) is None
        # and model_fields_set contains the field
        if self.level_id is None and "level_id" in self.model_fields_set:
            _dict["levelId"] = None

        # set to None if currency_code (nullable) is None
        # and model_fields_set contains the field
        if self.currency_code is None and "currency_code" in self.model_fields_set:
            _dict["currencyCode"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of LevelsAndBandsPayBand from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "levelId": obj.get("levelId"),
                "min": obj.get("min"),
                "mid": obj.get("mid"),
                "max": obj.get("max"),
                "currencyCode": obj.get("currencyCode"),
                "percentageRange": obj.get("percentageRange"),
                "compensationType": obj.get("compensationType"),
            }
        )
        return _obj
