"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing_extensions import Self


class ListUsersXmlResponseUserInner(BaseModel):
    """
    ListUsersXmlResponseUserInner
    """

    id: StrictInt | None = Field(default=None, description="The user ID.")
    employee_id: StrictInt | None = Field(
        default=None,
        description="The employee record ID. Present as an XML attribute only when the user has an associated employee record.",
        alias="employeeId",
    )
    first_name: StrictStr | None = Field(default=None, description="First name.", alias="firstName")
    last_name: StrictStr | None = Field(default=None, description="Last name.", alias="lastName")
    email: StrictStr | None = Field(default=None, description="The user's email address.")
    status: StrictStr | None = Field(default=None, description="Account status.")
    last_login: datetime | None = Field(
        default=None,
        description="ISO 8601 timestamp of the most recent login. Omitted when the user has never logged in.",
        alias="lastLogin",
    )
    __properties: ClassVar[list[str]] = ["id", "employeeId", "firstName", "lastName", "email", "status", "lastLogin"]

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["enabled", "disabled"]):
            raise ValueError("must be one of enum values ('enabled', 'disabled')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ListUsersXmlResponseUserInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ListUsersXmlResponseUserInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "employeeId": obj.get("employeeId"),
                "firstName": obj.get("firstName"),
                "lastName": obj.get("lastName"),
                "email": obj.get("email"),
                "status": obj.get("status"),
                "lastLogin": obj.get("lastLogin"),
            }
        )
        return _obj
