# coding: utf-8

"""
    BambooHR API

    BambooHR API documentation. https://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ListUsersXmlResponseUserInner(BaseModel):
    """
    ListUsersXmlResponseUserInner
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The user ID.")
    employee_id: Optional[StrictInt] = Field(default=None, description="The employee record ID. Present as an XML attribute only when the user has an associated employee record.", alias="employeeId")
    first_name: Optional[StrictStr] = Field(default=None, description="First name.", alias="firstName")
    last_name: Optional[StrictStr] = Field(default=None, description="Last name.", alias="lastName")
    email: Optional[StrictStr] = Field(default=None, description="The user's email address.")
    status: Optional[StrictStr] = Field(default=None, description="Account status.")
    last_login: Optional[datetime] = Field(default=None, description="ISO 8601 timestamp of the most recent login. Omitted when the user has never logged in.", alias="lastLogin")
    __properties: ClassVar[List[str]] = ["id", "employeeId", "firstName", "lastName", "email", "status", "lastLogin"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['enabled', 'disabled']):
            raise ValueError("must be one of enum values ('enabled', 'disabled')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListUsersXmlResponseUserInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListUsersXmlResponseUserInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "employeeId": obj.get("employeeId"),
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "email": obj.get("email"),
            "status": obj.get("status"),
            "lastLogin": obj.get("lastLogin")
        })
        return _obj


