"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing_extensions import Self

from bamboohr_sdk.models.location_response_object_address import LocationResponseObjectAddress


class LocationResponseObject(BaseModel):
    """
    Transformer for location data with nested address structure
    """

    id: StrictStr | None = Field(default=None, description="Unique identifier for the location")
    label: StrictStr | None = Field(default=None, description="Display name for the location")
    archived: StrictBool | None = Field(default=None, description="Whether the location is archived")
    manageable: StrictBool | None = Field(default=None, description="Whether the location is manageable")
    address: LocationResponseObjectAddress | None = None
    created_at: datetime | None = Field(default=None, alias="createdAt")
    archived_at: datetime | None = Field(default=None, alias="archivedAt")
    __properties: ClassVar[list[str]] = ["id", "label", "archived", "manageable", "address", "createdAt", "archivedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of LocationResponseObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict["address"] = self.address.to_dict()
        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict["createdAt"] = None

        # set to None if archived_at (nullable) is None
        # and model_fields_set contains the field
        if self.archived_at is None and "archived_at" in self.model_fields_set:
            _dict["archivedAt"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of LocationResponseObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "label": obj.get("label"),
                "archived": obj.get("archived"),
                "manageable": obj.get("manageable"),
                "address": LocationResponseObjectAddress.from_dict(obj["address"])
                if obj.get("address") is not None
                else None,
                "createdAt": obj.get("createdAt"),
                "archivedAt": obj.get("archivedAt"),
            }
        )
        return _obj
