
"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Self

from bamboohr_sdk.models.country import Country
from bamboohr_sdk.models.state import State


class Location(BaseModel):
    """
    Location
    """

    id: StrictInt | None = Field(default=None, description="The ID of the location")
    name: StrictStr | None = Field(default=None, description="Name of the location")
    description: StrictStr | None = Field(default=None, description="Description of the location")
    city: StrictStr | None = Field(default=None, description="City of the location")
    state: State | None = None
    country: Country | None = None
    zipcode: StrictStr | None = Field(default=None, description="The ZIP or postal code of the location")
    address_line1: StrictStr | None = Field(
        default=None, description="The first address line of the location", alias="addressLine1"
    )
    address_line2: StrictStr | None = Field(
        default=None, description="The second address line of the location", alias="addressLine2"
    )
    phone: StrictStr | None = Field(default=None, description="The phone number of the location")
    __properties: ClassVar[list[str]] = [
        "id",
        "name",
        "description",
        "city",
        "state",
        "country",
        "zipcode",
        "addressLine1",
        "addressLine2",
        "phone",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of Location from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of state
        if self.state:
            _dict["state"] = self.state.to_dict()
        # override the default output from pydantic by calling `to_dict()` of country
        if self.country:
            _dict["country"] = self.country.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of Location from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "name": obj.get("name"),
                "description": obj.get("description"),
                "city": obj.get("city"),
                "state": State.from_dict(obj["state"]) if obj.get("state") is not None else None,
                "country": Country.from_dict(obj["country"]) if obj.get("country") is not None else None,
                "zipcode": obj.get("zipcode"),
                "addressLine1": obj.get("addressLine1"),
                "addressLine2": obj.get("addressLine2"),
                "phone": obj.get("phone"),
            }
        )
        return _obj
