"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing_extensions import Self


class Model1d64402ee192568adbd5e3179a91e6e2RequestInnerBudgetAllocations(BaseModel):
    """
    Model1d64402ee192568adbd5e3179a91e6e2RequestInnerBudgetAllocations
    """

    salary_increase: StrictFloat | StrictInt | None = Field(default=None, alias="salaryIncrease")
    bonuses: StrictFloat | StrictInt | None = None
    equity: StrictFloat | StrictInt | None = None
    __properties: ClassVar[list[str]] = ["salaryIncrease", "bonuses", "equity"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of Model1d64402ee192568adbd5e3179a91e6e2RequestInnerBudgetAllocations from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if salary_increase (nullable) is None
        # and model_fields_set contains the field
        if self.salary_increase is None and "salary_increase" in self.model_fields_set:
            _dict["salaryIncrease"] = None

        # set to None if bonuses (nullable) is None
        # and model_fields_set contains the field
        if self.bonuses is None and "bonuses" in self.model_fields_set:
            _dict["bonuses"] = None

        # set to None if equity (nullable) is None
        # and model_fields_set contains the field
        if self.equity is None and "equity" in self.model_fields_set:
            _dict["equity"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of Model1d64402ee192568adbd5e3179a91e6e2RequestInnerBudgetAllocations from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {"salaryIncrease": obj.get("salaryIncrease"), "bonuses": obj.get("bonuses"), "equity": obj.get("equity")}
        )
        return _obj
