"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing_extensions import Self


class NewHirePacketPublicApi(BaseModel):
    """
    Flat new hire packet instance for public read APIs (list and detail).
    """

    id: StrictInt | None = None
    employee_id: StrictInt | None = Field(
        default=None, description="Employee this packet belongs to.", alias="employeeId"
    )
    contact_employee_id: StrictInt | None = Field(default=None, alias="contactEmployeeId")
    requires_personal_information: StrictBool | None = Field(default=None, alias="requiresPersonalInformation")
    requires_photo: StrictBool | None = Field(default=None, alias="requiresPhoto")
    requires_personal_questions: StrictBool | None = Field(default=None, alias="requiresPersonalQuestions")
    arrive_by_time: StrictStr | None = Field(default=None, alias="arriveByTime")
    location: StrictStr | None = None
    sent_datetime: StrictStr | None = Field(default=None, alias="sentDatetime")
    viewed_datetime: StrictStr | None = Field(default=None, alias="viewedDatetime")
    completed_datetime: StrictStr | None = Field(default=None, alias="completedDatetime")
    created_by_user_id: StrictInt | None = Field(default=None, alias="createdByUserId")
    created_datetime: StrictStr | None = Field(default=None, alias="createdDatetime")
    send_get_to_know_you_email: StrictBool | None = Field(default=None, alias="sendGetToKnowYouEmail")
    get_to_know_you_email_sent: StrictBool | None = Field(default=None, alias="getToKnowYouEmailSent")
    show_payroll_state: StrictBool | None = Field(default=None, alias="showPayrollState")
    show_payroll_federal: StrictBool | None = Field(default=None, alias="showPayrollFederal")
    show_payroll_direct_deposit: StrictBool | None = Field(default=None, alias="showPayrollDirectDeposit")
    nhp_configuration_id: StrictInt | None = Field(default=None, alias="nhpConfigurationId")
    nhp_template_id: StrictInt | None = Field(default=None, alias="nhpTemplateId")
    count_nhp_gtky_sent: StrictInt | None = Field(default=None, alias="countNhpGtkySent")
    cancelled: StrictBool | None = None
    include_photo_option: StrictBool | None = Field(
        default=None,
        description="Whether photo collection is offered based on configuration.",
        alias="includePhotoOption",
    )
    status: StrictStr | None = Field(default=None, description="Derived lifecycle status for the instance.")
    __properties: ClassVar[list[str]] = [
        "id",
        "employeeId",
        "contactEmployeeId",
        "requiresPersonalInformation",
        "requiresPhoto",
        "requiresPersonalQuestions",
        "arriveByTime",
        "location",
        "sentDatetime",
        "viewedDatetime",
        "completedDatetime",
        "createdByUserId",
        "createdDatetime",
        "sendGetToKnowYouEmail",
        "getToKnowYouEmailSent",
        "showPayrollState",
        "showPayrollFederal",
        "showPayrollDirectDeposit",
        "nhpConfigurationId",
        "nhpTemplateId",
        "countNhpGtkySent",
        "cancelled",
        "includePhotoOption",
        "status",
    ]

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["cancelled", "completed", "sent", "draft"]):
            raise ValueError("must be one of enum values ('cancelled', 'completed', 'sent', 'draft')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of NewHirePacketPublicApi from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict["id"] = None

        # set to None if contact_employee_id (nullable) is None
        # and model_fields_set contains the field
        if self.contact_employee_id is None and "contact_employee_id" in self.model_fields_set:
            _dict["contactEmployeeId"] = None

        # set to None if arrive_by_time (nullable) is None
        # and model_fields_set contains the field
        if self.arrive_by_time is None and "arrive_by_time" in self.model_fields_set:
            _dict["arriveByTime"] = None

        # set to None if location (nullable) is None
        # and model_fields_set contains the field
        if self.location is None and "location" in self.model_fields_set:
            _dict["location"] = None

        # set to None if sent_datetime (nullable) is None
        # and model_fields_set contains the field
        if self.sent_datetime is None and "sent_datetime" in self.model_fields_set:
            _dict["sentDatetime"] = None

        # set to None if viewed_datetime (nullable) is None
        # and model_fields_set contains the field
        if self.viewed_datetime is None and "viewed_datetime" in self.model_fields_set:
            _dict["viewedDatetime"] = None

        # set to None if completed_datetime (nullable) is None
        # and model_fields_set contains the field
        if self.completed_datetime is None and "completed_datetime" in self.model_fields_set:
            _dict["completedDatetime"] = None

        # set to None if created_by_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.created_by_user_id is None and "created_by_user_id" in self.model_fields_set:
            _dict["createdByUserId"] = None

        # set to None if created_datetime (nullable) is None
        # and model_fields_set contains the field
        if self.created_datetime is None and "created_datetime" in self.model_fields_set:
            _dict["createdDatetime"] = None

        # set to None if get_to_know_you_email_sent (nullable) is None
        # and model_fields_set contains the field
        if self.get_to_know_you_email_sent is None and "get_to_know_you_email_sent" in self.model_fields_set:
            _dict["getToKnowYouEmailSent"] = None

        # set to None if show_payroll_state (nullable) is None
        # and model_fields_set contains the field
        if self.show_payroll_state is None and "show_payroll_state" in self.model_fields_set:
            _dict["showPayrollState"] = None

        # set to None if show_payroll_federal (nullable) is None
        # and model_fields_set contains the field
        if self.show_payroll_federal is None and "show_payroll_federal" in self.model_fields_set:
            _dict["showPayrollFederal"] = None

        # set to None if show_payroll_direct_deposit (nullable) is None
        # and model_fields_set contains the field
        if self.show_payroll_direct_deposit is None and "show_payroll_direct_deposit" in self.model_fields_set:
            _dict["showPayrollDirectDeposit"] = None

        # set to None if nhp_configuration_id (nullable) is None
        # and model_fields_set contains the field
        if self.nhp_configuration_id is None and "nhp_configuration_id" in self.model_fields_set:
            _dict["nhpConfigurationId"] = None

        # set to None if nhp_template_id (nullable) is None
        # and model_fields_set contains the field
        if self.nhp_template_id is None and "nhp_template_id" in self.model_fields_set:
            _dict["nhpTemplateId"] = None

        # set to None if count_nhp_gtky_sent (nullable) is None
        # and model_fields_set contains the field
        if self.count_nhp_gtky_sent is None and "count_nhp_gtky_sent" in self.model_fields_set:
            _dict["countNhpGtkySent"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of NewHirePacketPublicApi from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "employeeId": obj.get("employeeId"),
                "contactEmployeeId": obj.get("contactEmployeeId"),
                "requiresPersonalInformation": obj.get("requiresPersonalInformation"),
                "requiresPhoto": obj.get("requiresPhoto"),
                "requiresPersonalQuestions": obj.get("requiresPersonalQuestions"),
                "arriveByTime": obj.get("arriveByTime"),
                "location": obj.get("location"),
                "sentDatetime": obj.get("sentDatetime"),
                "viewedDatetime": obj.get("viewedDatetime"),
                "completedDatetime": obj.get("completedDatetime"),
                "createdByUserId": obj.get("createdByUserId"),
                "createdDatetime": obj.get("createdDatetime"),
                "sendGetToKnowYouEmail": obj.get("sendGetToKnowYouEmail"),
                "getToKnowYouEmailSent": obj.get("getToKnowYouEmailSent"),
                "showPayrollState": obj.get("showPayrollState"),
                "showPayrollFederal": obj.get("showPayrollFederal"),
                "showPayrollDirectDeposit": obj.get("showPayrollDirectDeposit"),
                "nhpConfigurationId": obj.get("nhpConfigurationId"),
                "nhpTemplateId": obj.get("nhpTemplateId"),
                "countNhpGtkySent": obj.get("countNhpGtkySent"),
                "cancelled": obj.get("cancelled"),
                "includePhotoOption": obj.get("includePhotoOption"),
                "status": obj.get("status"),
            }
        )
        return _obj
