"""
BambooHR API

BambooHR API documentation. https://documentation.bamboohr.com/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing_extensions import Self

from bamboohr_sdk.models.levels_and_bands_pay_band_value import LevelsAndBandsPayBandValue
from bamboohr_sdk.models.pay_grades_and_bands_level_job_title import PayGradesAndBandsLevelJobTitle


class PayGradesAndBandsLevel(BaseModel):
    """
    PayGradesAndBandsLevel
    """

    level_id: StrictInt | None = Field(default=None, alias="levelId")
    level_name: StrictStr | None = Field(default=None, alias="levelName")
    min: LevelsAndBandsPayBandValue | None = Field(
        default=None, description="Minimum pay band value with its own validation state."
    )
    mid: LevelsAndBandsPayBandValue | None = Field(
        default=None, description="Midpoint pay band value with its own validation state."
    )
    max: LevelsAndBandsPayBandValue | None = Field(
        default=None, description="Maximum pay band value with its own validation state."
    )
    percentage_range: LevelsAndBandsPayBandValue | None = Field(
        default=None,
        description="Percentage-range pay band value with its own validation state; its `value` is null for min-mid-max bands.",
        alias="percentageRange",
    )
    currency_code: StrictStr | None = Field(default=None, alias="currencyCode")
    compensation_type: StrictStr | None = Field(
        default=None, description="Compensation type for the level.", alias="compensationType"
    )
    job_titles: list[PayGradesAndBandsLevelJobTitle] | None = Field(
        default=None, description="Job titles assigned to this level.", alias="jobTitles"
    )
    errors: list[StrictStr | None] | None = Field(default=None, description="Validation errors for this level.")
    warnings: list[StrictStr | None] | None = Field(default=None, description="Validation warnings for this level.")
    __properties: ClassVar[list[str]] = [
        "levelId",
        "levelName",
        "min",
        "mid",
        "max",
        "percentageRange",
        "currencyCode",
        "compensationType",
        "jobTitles",
        "errors",
        "warnings",
    ]

    @field_validator("compensation_type")
    def compensation_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["Salary", "Hourly"]):
            raise ValueError("must be one of enum values ('Salary', 'Hourly')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of PayGradesAndBandsLevel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of min
        if self.min:
            _dict["min"] = self.min.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mid
        if self.mid:
            _dict["mid"] = self.mid.to_dict()
        # override the default output from pydantic by calling `to_dict()` of max
        if self.max:
            _dict["max"] = self.max.to_dict()
        # override the default output from pydantic by calling `to_dict()` of percentage_range
        if self.percentage_range:
            _dict["percentageRange"] = self.percentage_range.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in job_titles (list)
        _items = []
        if self.job_titles:
            for _item_job_titles in self.job_titles:
                if _item_job_titles:
                    _items.append(_item_job_titles.to_dict())
            _dict["jobTitles"] = _items
        # set to None if level_id (nullable) is None
        # and model_fields_set contains the field
        if self.level_id is None and "level_id" in self.model_fields_set:
            _dict["levelId"] = None

        # set to None if level_name (nullable) is None
        # and model_fields_set contains the field
        if self.level_name is None and "level_name" in self.model_fields_set:
            _dict["levelName"] = None

        # set to None if currency_code (nullable) is None
        # and model_fields_set contains the field
        if self.currency_code is None and "currency_code" in self.model_fields_set:
            _dict["currencyCode"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of PayGradesAndBandsLevel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "levelId": obj.get("levelId"),
                "levelName": obj.get("levelName"),
                "min": LevelsAndBandsPayBandValue.from_dict(obj["min"]) if obj.get("min") is not None else None,
                "mid": LevelsAndBandsPayBandValue.from_dict(obj["mid"]) if obj.get("mid") is not None else None,
                "max": LevelsAndBandsPayBandValue.from_dict(obj["max"]) if obj.get("max") is not None else None,
                "percentageRange": LevelsAndBandsPayBandValue.from_dict(obj["percentageRange"])
                if obj.get("percentageRange") is not None
                else None,
                "currencyCode": obj.get("currencyCode"),
                "compensationType": obj.get("compensationType"),
                "jobTitles": [PayGradesAndBandsLevelJobTitle.from_dict(_item) for _item in obj["jobTitles"]]
                if obj.get("jobTitles") is not None
                else None,
                "errors": obj.get("errors"),
                "warnings": obj.get("warnings"),
            }
        )
        return _obj
