"""
BambooHR API

BambooHR API documentation. https://documentation.bamboohr.com/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Self

from bamboohr_sdk.models.pay_grades_and_bands_configuration_status_job_titles import (
    PayGradesAndBandsConfigurationStatusJobTitles,
)
from bamboohr_sdk.models.pay_grades_and_bands_configuration_status_levels import (
    PayGradesAndBandsConfigurationStatusLevels,
)
from bamboohr_sdk.models.pay_grades_and_bands_configuration_status_pay_bands import (
    PayGradesAndBandsConfigurationStatusPayBands,
)
from bamboohr_sdk.models.pay_grades_and_bands_configuration_status_review import (
    PayGradesAndBandsConfigurationStatusReview,
)


class PayGradesAndBandsConfigurationStatus(BaseModel):
    """
    PayGradesAndBandsConfigurationStatus
    """

    levels: PayGradesAndBandsConfigurationStatusLevels
    pay_bands: PayGradesAndBandsConfigurationStatusPayBands = Field(alias="payBands")
    job_titles: PayGradesAndBandsConfigurationStatusJobTitles = Field(alias="jobTitles")
    review: PayGradesAndBandsConfigurationStatusReview
    __properties: ClassVar[list[str]] = ["levels", "payBands", "jobTitles", "review"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of PayGradesAndBandsConfigurationStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of levels
        if self.levels:
            _dict["levels"] = self.levels.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pay_bands
        if self.pay_bands:
            _dict["payBands"] = self.pay_bands.to_dict()
        # override the default output from pydantic by calling `to_dict()` of job_titles
        if self.job_titles:
            _dict["jobTitles"] = self.job_titles.to_dict()
        # override the default output from pydantic by calling `to_dict()` of review
        if self.review:
            _dict["review"] = self.review.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of PayGradesAndBandsConfigurationStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "levels": PayGradesAndBandsConfigurationStatusLevels.from_dict(obj["levels"])
                if obj.get("levels") is not None
                else None,
                "payBands": PayGradesAndBandsConfigurationStatusPayBands.from_dict(obj["payBands"])
                if obj.get("payBands") is not None
                else None,
                "jobTitles": PayGradesAndBandsConfigurationStatusJobTitles.from_dict(obj["jobTitles"])
                if obj.get("jobTitles") is not None
                else None,
                "review": PayGradesAndBandsConfigurationStatusReview.from_dict(obj["review"])
                if obj.get("review") is not None
                else None,
            }
        )
        return _obj
