"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Self


class SchedulingScheduleV1(BaseModel):
    """
    A shift schedule for a specific location, which organizes shifts for employees
    """

    id: UUID | None = Field(default=None, description="The UUID of the schedule")
    name: StrictStr | None = Field(default=None, description="The name of the schedule")
    location_id: StrictInt | None = Field(
        default=None, description="The ID of the location the schedule belongs to", alias="locationId"
    )
    timezone: StrictStr | None = Field(
        default=None, description="The timezone of the schedule, provide if location is missing timezone"
    )
    start_of_week: StrictStr | None = Field(
        default=None, description="The starting day of the week for the schedule", alias="startOfWeek"
    )
    early_clock_in_threshold: StrictInt | None = Field(
        default=None,
        description="The threshold (in minutes) that an employee is allowed to clock in early to a shift on this schedule",
        alias="earlyClockInThreshold",
    )
    manager_user_ids: list[StrictInt] | None = Field(
        default=None, description="What users manage this schedule", alias="managerUserIds"
    )
    employee_ids: list[StrictInt] | None = Field(
        default=None, description="What employees are assigned to this schedule", alias="employeeIds"
    )
    created_at: datetime | None = Field(
        default=None, description="UTC timestamp when the schedule was created", alias="createdAt"
    )
    updated_at: datetime | None = Field(default=None, alias="updatedAt")
    deleted_at: datetime | None = Field(default=None, alias="deletedAt")
    __properties: ClassVar[list[str]] = [
        "id",
        "name",
        "locationId",
        "timezone",
        "startOfWeek",
        "earlyClockInThreshold",
        "managerUserIds",
        "employeeIds",
        "createdAt",
        "updatedAt",
        "deletedAt",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of SchedulingScheduleV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: set[str] = set(
            [
                "id",
                "created_at",
                "updated_at",
                "deleted_at",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict["updatedAt"] = None

        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict["deletedAt"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of SchedulingScheduleV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "name": obj.get("name"),
                "locationId": obj.get("locationId"),
                "timezone": obj.get("timezone"),
                "startOfWeek": obj.get("startOfWeek"),
                "earlyClockInThreshold": obj.get("earlyClockInThreshold"),
                "managerUserIds": obj.get("managerUserIds"),
                "employeeIds": obj.get("employeeIds"),
                "createdAt": obj.get("createdAt"),
                "updatedAt": obj.get("updatedAt"),
                "deletedAt": obj.get("deletedAt"),
            }
        )
        return _obj
