"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing_extensions import Self


class SchedulingSchedulingShiftV1(BaseModel):
    """
    A shift for scheduling
    """

    id: StrictStr = Field(
        description="The ID of the shift. This can be the UUIDv7 of the shift instance, or a composite ID (<recurringShiftDefinitionId>_<recurrenceId>) for uninstantiated recurring shifts."
    )
    schedule_id: UUID = Field(description="The ID of the schedule the shift belongs to.", alias="scheduleId")
    name: StrictStr | None = None
    status: StrictStr = Field(description="The status of the shift.")
    color: StrictStr = Field(description="6 character color hex code.")
    capacity: StrictInt | None = None
    start: datetime | None
    end: datetime | None
    timezone: StrictStr = Field(description="The timezone for the shift.")
    recurrence_rule: StrictStr | None = Field(default=None, alias="recurrenceRule")
    recurrence_id: StrictStr | None = Field(default=None, alias="recurrenceId")
    recurrence_dtstart: StrictStr | None = Field(default=None, alias="recurrenceDtstart")
    recurrence_dtend: StrictStr | None = Field(default=None, alias="recurrenceDtend")
    recurrence_until: StrictStr | None = Field(default=None, alias="recurrenceUntil")
    employee_ids: list[StrictInt] | None = Field(
        default=None, description="The list of employee IDs currently assigned.", alias="employeeIds"
    )
    unpublished_changes: dict[str, Any] | None = Field(default=None, alias="unpublishedChanges")
    created_at: datetime | None = Field(
        default=None, description="UTC timestamp when the shift was created", alias="createdAt"
    )
    updated_at: datetime | None = Field(default=None, alias="updatedAt")
    deleted_at: datetime | None = Field(default=None, alias="deletedAt")
    __properties: ClassVar[list[str]] = [
        "id",
        "scheduleId",
        "name",
        "status",
        "color",
        "capacity",
        "start",
        "end",
        "timezone",
        "recurrenceRule",
        "recurrenceId",
        "recurrenceDtstart",
        "recurrenceDtend",
        "recurrenceUntil",
        "employeeIds",
        "unpublishedChanges",
        "createdAt",
        "updatedAt",
        "deletedAt",
    ]

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["planned", "published", "cancelled", "deleted"]):
            raise ValueError("must be one of enum values ('planned', 'published', 'cancelled', 'deleted')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of SchedulingSchedulingShiftV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: set[str] = set(
            [
                "id",
                "created_at",
                "updated_at",
                "deleted_at",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict["name"] = None

        # set to None if capacity (nullable) is None
        # and model_fields_set contains the field
        if self.capacity is None and "capacity" in self.model_fields_set:
            _dict["capacity"] = None

        # set to None if start (nullable) is None
        # and model_fields_set contains the field
        if self.start is None and "start" in self.model_fields_set:
            _dict["start"] = None

        # set to None if end (nullable) is None
        # and model_fields_set contains the field
        if self.end is None and "end" in self.model_fields_set:
            _dict["end"] = None

        # set to None if recurrence_rule (nullable) is None
        # and model_fields_set contains the field
        if self.recurrence_rule is None and "recurrence_rule" in self.model_fields_set:
            _dict["recurrenceRule"] = None

        # set to None if recurrence_id (nullable) is None
        # and model_fields_set contains the field
        if self.recurrence_id is None and "recurrence_id" in self.model_fields_set:
            _dict["recurrenceId"] = None

        # set to None if recurrence_dtstart (nullable) is None
        # and model_fields_set contains the field
        if self.recurrence_dtstart is None and "recurrence_dtstart" in self.model_fields_set:
            _dict["recurrenceDtstart"] = None

        # set to None if recurrence_dtend (nullable) is None
        # and model_fields_set contains the field
        if self.recurrence_dtend is None and "recurrence_dtend" in self.model_fields_set:
            _dict["recurrenceDtend"] = None

        # set to None if recurrence_until (nullable) is None
        # and model_fields_set contains the field
        if self.recurrence_until is None and "recurrence_until" in self.model_fields_set:
            _dict["recurrenceUntil"] = None

        # set to None if unpublished_changes (nullable) is None
        # and model_fields_set contains the field
        if self.unpublished_changes is None and "unpublished_changes" in self.model_fields_set:
            _dict["unpublishedChanges"] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict["updatedAt"] = None

        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict["deletedAt"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of SchedulingSchedulingShiftV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "scheduleId": obj.get("scheduleId"),
                "name": obj.get("name"),
                "status": obj.get("status"),
                "color": obj.get("color"),
                "capacity": obj.get("capacity"),
                "start": obj.get("start"),
                "end": obj.get("end"),
                "timezone": obj.get("timezone"),
                "recurrenceRule": obj.get("recurrenceRule"),
                "recurrenceId": obj.get("recurrenceId"),
                "recurrenceDtstart": obj.get("recurrenceDtstart"),
                "recurrenceDtend": obj.get("recurrenceDtend"),
                "recurrenceUntil": obj.get("recurrenceUntil"),
                "employeeIds": obj.get("employeeIds"),
                "unpublishedChanges": obj.get("unpublishedChanges"),
                "createdAt": obj.get("createdAt"),
                "updatedAt": obj.get("updatedAt"),
                "deletedAt": obj.get("deletedAt"),
            }
        )
        return _obj
