"""
BambooHR API

BambooHR API documentation. https://documentation.bamboohr.com/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date, datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing_extensions import Self


class TimeTrackingTimesheetV1(BaseModel):
    """
    A pay period's time data for an employee.
    """

    id: StrictInt | None = Field(default=None, description="Identifier for the timesheet.")
    employee_id: StrictInt | None = Field(
        default=None, description="The employee this timesheet belongs to.", alias="employeeId"
    )
    type: StrictStr | None = Field(
        default=None, description="Tracking method snapshotted from the configuration at period start."
    )
    start_date: date | None = Field(
        default=None, description="First date of the pay period (inclusive).", alias="startDate"
    )
    end_date: date | None = Field(default=None, description="Last date of the pay period (inclusive).", alias="endDate")
    status: StrictStr | None = Field(default=None, description="Derived approval state.")
    total_hours: StrictFloat | StrictInt | None = Field(
        default=None,
        description="Sum of all hours across regular, overtime, holiday, and approved PTO.",
        alias="totalHours",
    )
    overtime_hours: StrictFloat | StrictInt | None = Field(
        default=None,
        description="Subset of totalHours that falls into the overtime rate bucket.",
        alias="overtimeHours",
    )
    approved_by: StrictInt | None = Field(default=None, alias="approvedBy")
    approved_at: datetime | None = Field(default=None, alias="approvedAt")
    created_at: datetime | None = Field(
        default=None, description="When the timesheet record was created.", alias="createdAt"
    )
    updated_at: datetime | None = Field(
        default=None, description="When the timesheet was last modified.", alias="updatedAt"
    )
    hours_last_changed_at: datetime | None = Field(
        default=None,
        description="When the timesheet's hours were last changed. Send this value back as the approval request's `lastChangedAt`. Distinct from `updatedAt` because hours are stored separately from the timesheet row.",
        alias="hoursLastChangedAt",
    )
    __properties: ClassVar[list[str]] = [
        "id",
        "employeeId",
        "type",
        "startDate",
        "endDate",
        "status",
        "totalHours",
        "overtimeHours",
        "approvedBy",
        "approvedAt",
        "createdAt",
        "updatedAt",
        "hoursLastChangedAt",
    ]

    @field_validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["SINGLE", "CLOCK", "MULTIPLE", "HOUR"]):
            raise ValueError("must be one of enum values ('SINGLE', 'CLOCK', 'MULTIPLE', 'HOUR')")
        return value

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["OPEN", "PENDING_APPROVAL", "APPROVED"]):
            raise ValueError("must be one of enum values ('OPEN', 'PENDING_APPROVAL', 'APPROVED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of TimeTrackingTimesheetV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: set[str] = set(
            [
                "hours_last_changed_at",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if approved_by (nullable) is None
        # and model_fields_set contains the field
        if self.approved_by is None and "approved_by" in self.model_fields_set:
            _dict["approvedBy"] = None

        # set to None if approved_at (nullable) is None
        # and model_fields_set contains the field
        if self.approved_at is None and "approved_at" in self.model_fields_set:
            _dict["approvedAt"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of TimeTrackingTimesheetV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "employeeId": obj.get("employeeId"),
                "type": obj.get("type"),
                "startDate": obj.get("startDate"),
                "endDate": obj.get("endDate"),
                "status": obj.get("status"),
                "totalHours": obj.get("totalHours"),
                "overtimeHours": obj.get("overtimeHours"),
                "approvedBy": obj.get("approvedBy"),
                "approvedAt": obj.get("approvedAt"),
                "createdAt": obj.get("createdAt"),
                "updatedAt": obj.get("updatedAt"),
                "hoursLastChangedAt": obj.get("hoursLastChangedAt"),
            }
        )
        return _obj
