
"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing_extensions import Self


class TimeTrackingTimeTrackingBreakAssessmentViolationV1(BaseModel):
    """
    A break assessment violation
    """

    assessment_id: UUID | None = Field(
        default=None, description="The unique identifier for the time tracking break assessment.", alias="assessmentId"
    )
    type: StrictStr | None = Field(default=None, description="The type of the violation")
    employee_timesheet_clock_entry_id: StrictFloat | StrictInt | None = Field(
        default=None, description="The id of the employee timesheet clock entry", alias="employeeTimesheetClockEntryId"
    )
    amount: StrictFloat | StrictInt | None = Field(default=None, description="The amount of the violation")
    __properties: ClassVar[list[str]] = ["assessmentId", "type", "employeeTimesheetClockEntryId", "amount"]

    @field_validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(
            ["break_started_early", "break_started_late", "break_ended_early", "break_ended_late", "break_missed"]
        ):
            raise ValueError(
                "must be one of enum values ('break_started_early', 'break_started_late', 'break_ended_early', 'break_ended_late', 'break_missed')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of TimeTrackingTimeTrackingBreakAssessmentViolationV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: set[str] = set(
            [
                "assessment_id",
                "type",
                "employee_timesheet_clock_entry_id",
                "amount",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if employee_timesheet_clock_entry_id (nullable) is None
        # and model_fields_set contains the field
        if (
            self.employee_timesheet_clock_entry_id is None
            and "employee_timesheet_clock_entry_id" in self.model_fields_set
        ):
            _dict["employeeTimesheetClockEntryId"] = None

        # set to None if amount (nullable) is None
        # and model_fields_set contains the field
        if self.amount is None and "amount" in self.model_fields_set:
            _dict["amount"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of TimeTrackingTimeTrackingBreakAssessmentViolationV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "assessmentId": obj.get("assessmentId"),
                "type": obj.get("type"),
                "employeeTimesheetClockEntryId": obj.get("employeeTimesheetClockEntryId"),
                "amount": obj.get("amount"),
            }
        )
        return _obj
