# coding: utf-8

"""
    BambooHR API

    BambooHR API documentation. https://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from bamboohr_sdk.models.time_tracking_time_tracking_break_assessment_violation_v1 import TimeTrackingTimeTrackingBreakAssessmentViolationV1
from typing import Optional, Set
from typing_extensions import Self

class TimeTrackingTimeTrackingBreakAssessmentV1(BaseModel):
    """
    A break assessment
    """ # noqa: E501
    id: Optional[UUID] = Field(default=None, description="The unique identifier for the time tracking break assessment")
    break_id: Optional[UUID] = Field(default=None, description="The unique identifier of the break", alias="breakId")
    employee_id: Optional[StrictInt] = Field(default=None, description="The id of the employee", alias="employeeId")
    employee_timesheet_id: Optional[StrictInt] = Field(default=None, description="The id of the employee timesheet", alias="employeeTimesheetId")
    var_date: Optional[date] = Field(default=None, description="The date of the break assessment", alias="date")
    timezone: Optional[StrictStr] = Field(default=None, description="The timezone of the break assessment")
    result: Optional[StrictStr] = Field(default=None, description="The result of the break assessment")
    available_ymdt: Optional[datetime] = Field(default=None, description="ISO 8601 timestamp when the break became available", alias="availableYmdt")
    unavailable_ymdt: Optional[datetime] = Field(default=None, description="ISO 8601 timestamp when the break became unavailable", alias="unavailableYmdt")
    created_at: Optional[datetime] = Field(default=None, description="ISO 8601 timestamp when the break was created", alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, description="ISO 8601 timestamp when the break was last updated", alias="updatedAt")
    violations: Optional[List[TimeTrackingTimeTrackingBreakAssessmentViolationV1]] = Field(default=None, description="Violations associated with the assessment ")
    clock_entry_ids: Optional[List[StrictInt]] = Field(default=None, description="Clock entry ids associated with the time tracking break assessment", alias="clockEntryIds")
    expected_duration: Optional[StrictInt] = Field(default=None, description="The expected duration of the break in minutes", alias="expectedDuration")
    recorded_duration: Optional[StrictInt] = Field(default=None, description="The recorded duration of the break in minutes", alias="recordedDuration")
    duration_difference: Optional[StrictInt] = Field(default=None, description="The difference between the expected and recorded duration in minutes", alias="durationDifference")
    __properties: ClassVar[List[str]] = ["id", "breakId", "employeeId", "employeeTimesheetId", "date", "timezone", "result", "availableYmdt", "unavailableYmdt", "createdAt", "updatedAt", "violations", "clockEntryIds", "expectedDuration", "recordedDuration", "durationDifference"]

    @field_validator('result')
    def result_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['compliant', 'violation', 'waived']):
            raise ValueError("must be one of enum values ('compliant', 'violation', 'waived')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TimeTrackingTimeTrackingBreakAssessmentV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "break_id",
            "available_ymdt",
            "unavailable_ymdt",
            "created_at",
            "updated_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in violations (list)
        _items = []
        if self.violations:
            for _item_violations in self.violations:
                if _item_violations:
                    _items.append(_item_violations.to_dict())
            _dict['violations'] = _items
        # set to None if available_ymdt (nullable) is None
        # and model_fields_set contains the field
        if self.available_ymdt is None and "available_ymdt" in self.model_fields_set:
            _dict['availableYmdt'] = None

        # set to None if unavailable_ymdt (nullable) is None
        # and model_fields_set contains the field
        if self.unavailable_ymdt is None and "unavailable_ymdt" in self.model_fields_set:
            _dict['unavailableYmdt'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updatedAt'] = None

        # set to None if expected_duration (nullable) is None
        # and model_fields_set contains the field
        if self.expected_duration is None and "expected_duration" in self.model_fields_set:
            _dict['expectedDuration'] = None

        # set to None if recorded_duration (nullable) is None
        # and model_fields_set contains the field
        if self.recorded_duration is None and "recorded_duration" in self.model_fields_set:
            _dict['recordedDuration'] = None

        # set to None if duration_difference (nullable) is None
        # and model_fields_set contains the field
        if self.duration_difference is None and "duration_difference" in self.model_fields_set:
            _dict['durationDifference'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TimeTrackingTimeTrackingBreakAssessmentV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "breakId": obj.get("breakId"),
            "employeeId": obj.get("employeeId"),
            "employeeTimesheetId": obj.get("employeeTimesheetId"),
            "date": obj.get("date"),
            "timezone": obj.get("timezone"),
            "result": obj.get("result"),
            "availableYmdt": obj.get("availableYmdt"),
            "unavailableYmdt": obj.get("unavailableYmdt"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "violations": [TimeTrackingTimeTrackingBreakAssessmentViolationV1.from_dict(_item) for _item in obj["violations"]] if obj.get("violations") is not None else None,
            "clockEntryIds": obj.get("clockEntryIds"),
            "expectedDuration": obj.get("expectedDuration"),
            "recordedDuration": obj.get("recordedDuration"),
            "durationDifference": obj.get("durationDifference")
        })
        return _obj


