"""
BambooHR API

BambooHR API documentation. https://documentation.bamboohr.com/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date, datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing_extensions import Self


class TimeTrackingEmployeeTimeTrackingDataV1(BaseModel):
    """
    An employee's time tracking enrollment.
    """

    id: StrictInt | None = Field(default=None, description="The ID of the enrollment record.")
    employee_id: StrictInt | None = Field(default=None, description="The ID of the employee.", alias="employeeId")
    configuration_id: StrictInt | None = Field(default=None, alias="configurationId")
    enabled: StrictBool | None = Field(default=None, description="Whether the employee is enrolled in time tracking.")
    enabled_on: date | None = Field(default=None, alias="enabledOn")
    timezone: StrictStr | None = None
    clock_in_id: StrictInt | None = Field(default=None, alias="clockInId")
    created_at: datetime | None = Field(
        default=None, description="ISO 8601 timestamp when the enrollment record was created.", alias="createdAt"
    )
    updated_at: datetime | None = Field(default=None, alias="updatedAt")
    __properties: ClassVar[list[str]] = [
        "id",
        "employeeId",
        "configurationId",
        "enabled",
        "enabledOn",
        "timezone",
        "clockInId",
        "createdAt",
        "updatedAt",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of TimeTrackingEmployeeTimeTrackingDataV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: set[str] = set(
            [
                "id",
                "timezone",
                "clock_in_id",
                "created_at",
                "updated_at",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if configuration_id (nullable) is None
        # and model_fields_set contains the field
        if self.configuration_id is None and "configuration_id" in self.model_fields_set:
            _dict["configurationId"] = None

        # set to None if enabled_on (nullable) is None
        # and model_fields_set contains the field
        if self.enabled_on is None and "enabled_on" in self.model_fields_set:
            _dict["enabledOn"] = None

        # set to None if timezone (nullable) is None
        # and model_fields_set contains the field
        if self.timezone is None and "timezone" in self.model_fields_set:
            _dict["timezone"] = None

        # set to None if clock_in_id (nullable) is None
        # and model_fields_set contains the field
        if self.clock_in_id is None and "clock_in_id" in self.model_fields_set:
            _dict["clockInId"] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict["updatedAt"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of TimeTrackingEmployeeTimeTrackingDataV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "employeeId": obj.get("employeeId"),
                "configurationId": obj.get("configurationId"),
                "enabled": obj.get("enabled"),
                "enabledOn": obj.get("enabledOn"),
                "timezone": obj.get("timezone"),
                "clockInId": obj.get("clockInId"),
                "createdAt": obj.get("createdAt"),
                "updatedAt": obj.get("updatedAt"),
            }
        )
        return _obj
