
"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing_extensions import Self

from bamboohr_sdk.models.time_tracking_create_or_update_time_tracking_break_without_policy_v1 import (
    TimeTrackingCreateOrUpdateTimeTrackingBreakWithoutPolicyV1,
)


class TimeTrackingCreateTimeTrackingBreakPolicyV1(BaseModel):
    """
    Data contract for creating a break policy
    """

    name: StrictStr = Field(description="Name of the break policy")
    description: StrictStr | None = Field(default=None, description="Optional description of the break policy")
    all_employees_assigned: StrictBool | None = Field(
        default=None,
        description="Whether all employees are assigned to this break policy",
        alias="allEmployeesAssigned",
    )
    breaks: list[TimeTrackingCreateOrUpdateTimeTrackingBreakWithoutPolicyV1] | None = Field(
        default=None, description="Collection of time tracking breaks to create or update without a policy"
    )
    employee_ids: list[StrictInt] | None = Field(
        default=None, description="The employees that should be assigned to this policy", alias="employeeIds"
    )
    __properties: ClassVar[list[str]] = ["name", "description", "allEmployeesAssigned", "breaks", "employeeIds"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of TimeTrackingCreateTimeTrackingBreakPolicyV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in breaks (list)
        _items = []
        if self.breaks:
            for _item_breaks in self.breaks:
                if _item_breaks:
                    _items.append(_item_breaks.to_dict())
            _dict["breaks"] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict["description"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of TimeTrackingCreateTimeTrackingBreakPolicyV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "description": obj.get("description"),
                "allEmployeesAssigned": obj.get("allEmployeesAssigned"),
                "breaks": [
                    TimeTrackingCreateOrUpdateTimeTrackingBreakWithoutPolicyV1.from_dict(_item)
                    for _item in obj["breaks"]
                ]
                if obj.get("breaks") is not None
                else None,
                "employeeIds": obj.get("employeeIds"),
            }
        )
        return _obj
