"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Self

from bamboohr_sdk.models.total_rewards_benefit_details_values import TotalRewardsBenefitDetailsValues
from bamboohr_sdk.models.total_rewards_comp_summary_values import TotalRewardsCompSummaryValues


class TotalRewardsBenefitSectionValues(BaseModel):
    """
    Schema for a total rewards benefit section
    """

    comp_summary: TotalRewardsCompSummaryValues | None = Field(
        default=None, description="Compensation summary", alias="compSummary"
    )
    benefit_details: list[TotalRewardsBenefitDetailsValues] | None = Field(
        default=None, description="Benefit details", alias="benefitDetails"
    )
    __properties: ClassVar[list[str]] = ["compSummary", "benefitDetails"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of TotalRewardsBenefitSectionValues from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of comp_summary
        if self.comp_summary:
            _dict["compSummary"] = self.comp_summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in benefit_details (list)
        _items = []
        if self.benefit_details:
            for _item_benefit_details in self.benefit_details:
                if _item_benefit_details:
                    _items.append(_item_benefit_details.to_dict())
            _dict["benefitDetails"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of TotalRewardsBenefitSectionValues from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "compSummary": TotalRewardsCompSummaryValues.from_dict(obj["compSummary"])
                if obj.get("compSummary") is not None
                else None,
                "benefitDetails": [TotalRewardsBenefitDetailsValues.from_dict(_item) for _item in obj["benefitDetails"]]
                if obj.get("benefitDetails") is not None
                else None,
            }
        )
        return _obj
