"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Self


class TotalRewardsEquityGrowthEstimation(BaseModel):
    """
    Schema for total rewards equity growth estimation
    """

    stop: StrictInt | None = Field(default=None, description="Stop")
    company_valuation: StrictStr | None = Field(default=None, description="Company valuation", alias="companyValuation")
    company_valuation_subvalue: StrictStr | None = Field(default=None, alias="companyValuationSubvalue")
    total_value: StrictStr | None = Field(default=None, description="Total value", alias="totalValue")
    total_value_subvalue: StrictStr | None = Field(default=None, alias="totalValueSubvalue")
    vested_value: StrictStr | None = Field(default=None, description="Vested amount value", alias="vestedValue")
    vested_value_subvalue: StrictStr | None = Field(default=None, alias="vestedValueSubvalue")
    __properties: ClassVar[list[str]] = [
        "stop",
        "companyValuation",
        "companyValuationSubvalue",
        "totalValue",
        "totalValueSubvalue",
        "vestedValue",
        "vestedValueSubvalue",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of TotalRewardsEquityGrowthEstimation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if company_valuation_subvalue (nullable) is None
        # and model_fields_set contains the field
        if self.company_valuation_subvalue is None and "company_valuation_subvalue" in self.model_fields_set:
            _dict["companyValuationSubvalue"] = None

        # set to None if total_value_subvalue (nullable) is None
        # and model_fields_set contains the field
        if self.total_value_subvalue is None and "total_value_subvalue" in self.model_fields_set:
            _dict["totalValueSubvalue"] = None

        # set to None if vested_value_subvalue (nullable) is None
        # and model_fields_set contains the field
        if self.vested_value_subvalue is None and "vested_value_subvalue" in self.model_fields_set:
            _dict["vestedValueSubvalue"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of TotalRewardsEquityGrowthEstimation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "stop": obj.get("stop"),
                "companyValuation": obj.get("companyValuation"),
                "companyValuationSubvalue": obj.get("companyValuationSubvalue"),
                "totalValue": obj.get("totalValue"),
                "totalValueSubvalue": obj.get("totalValueSubvalue"),
                "vestedValue": obj.get("vestedValue"),
                "vestedValueSubvalue": obj.get("vestedValueSubvalue"),
            }
        )
        return _obj
