"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing_extensions import Self


class TotalRewardsEquityGrowthChartItem(BaseModel):
    """
    Schema for total rewards equity growth chart item
    """

    label: StrictStr | None = Field(default=None, description="Label")
    estimated_net_value: StrictStr | None = Field(
        default=None, description="Estimated value", alias="estimatedNetValue"
    )
    subvalue: StrictStr | None = None
    vested: StrictFloat | StrictInt | None = None
    current: StrictFloat | StrictInt | None = None
    unvested: StrictFloat | StrictInt | None = None
    __properties: ClassVar[list[str]] = ["label", "estimatedNetValue", "subvalue", "vested", "current", "unvested"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of TotalRewardsEquityGrowthChartItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if subvalue (nullable) is None
        # and model_fields_set contains the field
        if self.subvalue is None and "subvalue" in self.model_fields_set:
            _dict["subvalue"] = None

        # set to None if vested (nullable) is None
        # and model_fields_set contains the field
        if self.vested is None and "vested" in self.model_fields_set:
            _dict["vested"] = None

        # set to None if current (nullable) is None
        # and model_fields_set contains the field
        if self.current is None and "current" in self.model_fields_set:
            _dict["current"] = None

        # set to None if unvested (nullable) is None
        # and model_fields_set contains the field
        if self.unvested is None and "unvested" in self.model_fields_set:
            _dict["unvested"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of TotalRewardsEquityGrowthChartItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "label": obj.get("label"),
                "estimatedNetValue": obj.get("estimatedNetValue"),
                "subvalue": obj.get("subvalue"),
                "vested": obj.get("vested"),
                "current": obj.get("current"),
                "unvested": obj.get("unvested"),
            }
        )
        return _obj
