"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing_extensions import Self

from bamboohr_sdk.models.total_rewards_equity_growth_estimation import TotalRewardsEquityGrowthEstimation


class TotalRewardsEquityEstimatedValuationValues(BaseModel):
    """
    Schema for total rewards equity growth valuation
    """

    equity_growth_estimation_items: list[TotalRewardsEquityGrowthEstimation] | None = Field(
        default=None, description="Equity estimated growth items", alias="equityGrowthEstimationItems"
    )
    number_of_vested_shares: StrictInt | None = Field(
        default=None, description="Number of vested shares", alias="numberOfVestedShares"
    )
    number_of_total_shares: StrictInt | None = Field(
        default=None, description="Number of total shares", alias="numberOfTotalShares"
    )
    equity_growth_slider_max: StrictInt | None = Field(default=None, alias="equityGrowthSliderMax")
    equity_growth_slider_min: StrictInt | None = Field(default=None, alias="equityGrowthSliderMin")
    __properties: ClassVar[list[str]] = [
        "equityGrowthEstimationItems",
        "numberOfVestedShares",
        "numberOfTotalShares",
        "equityGrowthSliderMax",
        "equityGrowthSliderMin",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of TotalRewardsEquityEstimatedValuationValues from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in equity_growth_estimation_items (list)
        _items = []
        if self.equity_growth_estimation_items:
            for _item_equity_growth_estimation_items in self.equity_growth_estimation_items:
                if _item_equity_growth_estimation_items:
                    _items.append(_item_equity_growth_estimation_items.to_dict())
            _dict["equityGrowthEstimationItems"] = _items
        # set to None if equity_growth_slider_max (nullable) is None
        # and model_fields_set contains the field
        if self.equity_growth_slider_max is None and "equity_growth_slider_max" in self.model_fields_set:
            _dict["equityGrowthSliderMax"] = None

        # set to None if equity_growth_slider_min (nullable) is None
        # and model_fields_set contains the field
        if self.equity_growth_slider_min is None and "equity_growth_slider_min" in self.model_fields_set:
            _dict["equityGrowthSliderMin"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of TotalRewardsEquityEstimatedValuationValues from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "equityGrowthEstimationItems": [
                    TotalRewardsEquityGrowthEstimation.from_dict(_item) for _item in obj["equityGrowthEstimationItems"]
                ]
                if obj.get("equityGrowthEstimationItems") is not None
                else None,
                "numberOfVestedShares": obj.get("numberOfVestedShares"),
                "numberOfTotalShares": obj.get("numberOfTotalShares"),
                "equityGrowthSliderMax": obj.get("equityGrowthSliderMax"),
                "equityGrowthSliderMin": obj.get("equityGrowthSliderMin"),
            }
        )
        return _obj
