
"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing_extensions import Self


class TrainingRecord(BaseModel):
    """
    TrainingRecord
    """

    id: StrictInt | None = Field(default=None, description="The ID of the training record.")
    employee_id: StrictInt | None = Field(
        default=None, description="The ID of the employee associated with the training.", alias="employeeId"
    )
    completed: StrictStr | None = Field(default=None, description="Completed is a date in the format yyyy-mm-dd.")
    notes: StrictStr | None = Field(default=None, description="Notes left on the training record.")
    instructor: StrictStr | None = Field(default=None, description="Name of the instructor.")
    credits: StrictFloat | StrictInt | None = Field(
        default=None, description="What was credited for the training record."
    )
    hours: StrictFloat | StrictInt | None = Field(
        default=None, description="Hours associated with the training record."
    )
    cost: StrictStr | None = Field(default=None, description="The currency and cost for the training record.")
    type: StrictInt | None = Field(default=None, description="The training type ID.")
    __properties: ClassVar[list[str]] = [
        "id",
        "employeeId",
        "completed",
        "notes",
        "instructor",
        "credits",
        "hours",
        "cost",
        "type",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of TrainingRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of TrainingRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "employeeId": obj.get("employeeId"),
                "completed": obj.get("completed"),
                "notes": obj.get("notes"),
                "instructor": obj.get("instructor"),
                "credits": obj.get("credits"),
                "hours": obj.get("hours"),
                "cost": obj.get("cost"),
                "type": obj.get("type"),
            }
        )
        return _obj
