# coding: utf-8

"""
    BambooHR API

    BambooHR API documentation. https://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class TransformedApiGoalMilestonesInner(BaseModel):
    """
    TransformedApiGoalMilestonesInner
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The id of the milestone.")
    employee_goal_id: Optional[StrictInt] = Field(default=None, description="The id of the goal which encompasses this milestone.", alias="employeeGoalId")
    title: Optional[StrictStr] = Field(default=None, description="The title of the milestone.")
    current_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The current value for a numeric milestone. This number will be rounded to the nearest hundredth. On the creation of a numeric milestone this value will automatically be set to the start value of the milestone. If the milestone is a simple checkbox milestone, this value will always be null.", alias="currentValue")
    start_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The starting value for a numeric milestone. This number will be rounded to the nearest hundredth. If the milestone is a simple checkbox milestone, this value will always be null.", alias="startValue")
    end_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The end goal for a numeric milestone. This number will be rounded to the nearest hundredth. If the milestone is a simple checkbox milestone, this value will always be null.", alias="endValue")
    completed_date_time: Optional[StrictStr] = Field(default=None, description="The date and time in which the goal has been completed. If the goal is not completed the value will be null.", alias="completedDateTime")
    last_update_date_time: Optional[StrictStr] = Field(default=None, description="The date and time in which the goal was last updated.", alias="lastUpdateDateTime")
    last_update_user_id: Optional[StrictInt] = Field(default=None, description="The ID of the user who last updated this milestone.", alias="lastUpdateUserId")
    __properties: ClassVar[List[str]] = ["id", "employeeGoalId", "title", "currentValue", "startValue", "endValue", "completedDateTime", "lastUpdateDateTime", "lastUpdateUserId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransformedApiGoalMilestonesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if current_value (nullable) is None
        # and model_fields_set contains the field
        if self.current_value is None and "current_value" in self.model_fields_set:
            _dict['currentValue'] = None

        # set to None if start_value (nullable) is None
        # and model_fields_set contains the field
        if self.start_value is None and "start_value" in self.model_fields_set:
            _dict['startValue'] = None

        # set to None if end_value (nullable) is None
        # and model_fields_set contains the field
        if self.end_value is None and "end_value" in self.model_fields_set:
            _dict['endValue'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransformedApiGoalMilestonesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "employeeGoalId": obj.get("employeeGoalId"),
            "title": obj.get("title"),
            "currentValue": obj.get("currentValue"),
            "startValue": obj.get("startValue"),
            "endValue": obj.get("endValue"),
            "completedDateTime": obj.get("completedDateTime"),
            "lastUpdateDateTime": obj.get("lastUpdateDateTime"),
            "lastUpdateUserId": obj.get("lastUpdateUserId")
        })
        return _obj


