
"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class WebhookEventType(str, Enum):
    """
    The type of event that triggers a webhook. Cannot mix employee_with_fields events with employee events. This list will be expanded in the future.
    """

    """
    allowed enum values
    """
    EMPLOYEE_WITH_FIELDS_DOT_UPDATED = "employee_with_fields.updated"
    EMPLOYEE_WITH_FIELDS_DOT_CREATED = "employee_with_fields.created"
    EMPLOYEE_WITH_FIELDS_DOT_DELETED = "employee_with_fields.deleted"
    EMPLOYEE_DOT_CREATED = "employee.created"
    EMPLOYEE_DOT_UPDATED = "employee.updated"
    EMPLOYEE_DOT_DELETED = "employee.deleted"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WebhookEventType from a JSON string"""
        return cls(json.loads(json_str))
