# coding: utf-8

"""
    BambooHR API

    BambooHR API documentation. https://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WebhooksListWebhooksInner(BaseModel):
    """
    WebhooksListWebhooksInner
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="The ID of the webhook.")
    name: Optional[StrictStr] = Field(default=None, description="The name of the webhook.")
    created: Optional[StrictStr] = Field(default=None, description="Datetime when the webhook was created (UTC, format: YYYY-MM-DD HH:MM:SS).")
    last_sent: Optional[StrictStr] = Field(default=None, description="Datetime when the webhook was last fired (UTC, format: YYYY-MM-DD HH:MM:SS). Null if the webhook has never fired.", alias="lastSent")
    url: Optional[StrictStr] = Field(default=None, description="The URL the webhook sends data to.")
    __properties: ClassVar[List[str]] = ["id", "name", "created", "lastSent", "url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhooksListWebhooksInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if last_sent (nullable) is None
        # and model_fields_set contains the field
        if self.last_sent is None and "last_sent" in self.model_fields_set:
            _dict['lastSent'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhooksListWebhooksInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "created": obj.get("created"),
            "lastSent": obj.get("lastSent"),
            "url": obj.get("url")
        })
        return _obj


