"""
BambooHR API

BambooHR API documentation. https://documentation.bamboohr.com/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Self

from bamboohr_sdk.models.whos_out_list_response_v1_links import WhosOutListResponseV1Links
from bamboohr_sdk.models.whos_out_list_response_v1_meta import WhosOutListResponseV1Meta
from bamboohr_sdk.models.whos_out_person_v1 import WhosOutPersonV1
from bamboohr_sdk.models.whos_out_v1 import WhosOutV1


class WhosOutListResponseV1(BaseModel):
    """
    WhosOutListResponseV1
    """

    data: list[WhosOutV1] | None = Field(default=None, description="Collection of approved time off occurrences")
    persons: dict[str, WhosOutPersonV1] | None = Field(
        default=None, description="Employee display data keyed by employee id. Present only when includePersons=true."
    )
    links: WhosOutListResponseV1Links | None = Field(default=None, alias="_links")
    meta: WhosOutListResponseV1Meta | None = None
    __properties: ClassVar[list[str]] = ["data", "persons", "_links", "meta"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of WhosOutListResponseV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item_data in self.data:
                if _item_data:
                    _items.append(_item_data.to_dict())
            _dict["data"] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in persons (dict)
        _field_dict = {}
        if self.persons:
            for _key_persons in self.persons:
                if self.persons[_key_persons]:
                    _field_dict[_key_persons] = self.persons[_key_persons].to_dict()
            _dict["persons"] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict["_links"] = self.links.to_dict()
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict["meta"] = self.meta.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of WhosOutListResponseV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "data": [WhosOutV1.from_dict(_item) for _item in obj["data"]] if obj.get("data") is not None else None,
                "persons": dict((_k, WhosOutPersonV1.from_dict(_v)) for _k, _v in obj["persons"].items())
                if obj.get("persons") is not None
                else None,
                "_links": WhosOutListResponseV1Links.from_dict(obj["_links"])
                if obj.get("_links") is not None
                else None,
                "meta": WhosOutListResponseV1Meta.from_dict(obj["meta"]) if obj.get("meta") is not None else None,
            }
        )
        return _obj
