
"""
BambooHR API

BambooHR API documentation. https://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Self

from bamboohr_sdk.models.xml_directory_employee_fieldset_field_inner import XmlDirectoryEmployeeFieldsetFieldInner


class XmlDirectoryEmployeeFieldset(BaseModel):
    """
    Field definitions
    """

    var_field: list[XmlDirectoryEmployeeFieldsetFieldInner] | None = Field(default=None, alias="field")
    __properties: ClassVar[list[str]] = ["field"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of XmlDirectoryEmployeeFieldset from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in var_field (list)
        _items = []
        if self.var_field:
            for _item_var_field in self.var_field:
                if _item_var_field:
                    _items.append(_item_var_field.to_dict())
            _dict["field"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of XmlDirectoryEmployeeFieldset from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "field": [XmlDirectoryEmployeeFieldsetFieldInner.from_dict(_item) for _item in obj["field"]]
                if obj.get("field") is not None
                else None
            }
        )
        return _obj
